### ISSUE TITLE
Dropdown Container does not toggle if  clicked on other dropdown

### ISSUE THREAD

**Issue by Navpreet7** [manishjanky/ngx-select-dropdown#10]
I have applied ngx-select-dropdown at two fields in my form, but the functionality of closing the div container at document click is not working in case I click on the second dropdown.

**Comment by manishjanky** [comment]
@Navpreet7 Thanks for pointing this out. 

Will have a look and update you soon.

**Comment by Navpreet7** [comment]
update me today if you have time , Actually your functionality to close the container on document click is not working when clicked on the another drop down button

**Comment by manishjanky** [comment]
@Navpreet7 yes have figured that out. If more than one instances are present it won't close the other. This was a decision that i took while developing this component as if don't stop the event from propagating it had other side effects.

Working on it. Will update as soon as i figure out how to handle this situation.

**Comment by Navpreet7** [comment]
have you got any solution?  Its urgent for me.

**Comment by Navpreet7** [comment]
I tried to use the approach of the element reference, to catch the target element and check if the current drop-down is open but that does not work.

renderer.listenGlobal("document", "click", (event: any) => {
            if (event.target && this.elem.nativeElement !== event.target && !this.elem.nativeElement.contains(event.target)) {
                this.toggleDropDown= false;
            }
        });

**Comment by manishjanky** [comment]
@Navpreet7  i have sort found an approach. Working on it will update you by EOD most probably.

**Comment by Navpreet7** [comment]
ok please do it asap :)

**Comment by manishjanky** [comment]
@Navpreet7  have fixed this please update the package to latest version.

Please test and let me know if this resolves your problem.

**Comment by Navpreet7** [comment]
Thanks Its working,
One thing more when I initialize the drop-down and select first time any value from available items. the selected item is not getting deleted from available items.
This is happing only first time after init.

**Comment by manishjanky** [comment]
OK let me have a look.

**Comment by Navpreet7** [comment]
I have done some changes in my ts according to my requirement. PFB my typescript code:
import {
  Component,
  OnInit,
  Input,
  EventEmitter,
  Output,
  HostListener,
  Renderer,
  OnChanges, SimpleChanges
} from "@angular/core";
import { Subject } from "rxjs/Subject";
import "rxjs/Rx";

@Component({
  selector: "ngx-select-dropdown",
  templateUrl: "./ngx-select-dropdown.component.html",
  styleUrls: ["./ngx-select-dropdown.component.scss"],
  host: {
    "(document:click)": "onClick($event)"
  }
})
export class SelectDropDownComponent implements OnInit {
  /**
   * Get the required inputs
   */
  @Input() public options: any;

  /**
   * configuration options
   */
  @Input() public config: any;

  /**
   * Whether multiple selection or single selection allowed
   */
  @Input() public multiple: boolean = false;
  @Input() public mode: string;
  /**
   * Value
   */
  @Input() public value: any;

  /**
   * event when value changes to update in the UI
   */
  @Output() public valueChange: EventEmitter<any> = new EventEmitter();
  /**
   * change event when value changes to provide user to handle things in change event
   */
  @Output() public change: EventEmitter<any> = new EventEmitter();
  @Output() public clicked: EventEmitter<any> = new EventEmitter();

  /**
   * Toogle the dropdown list
   */
  public toggleDropdown: boolean = false;

  /**
   * Available items for selection
   */
  public availableItems: any = [];

  /**
   * Selected Items
   */
  public selectedItems: any = [];

  /**
   * Selction text to be Displayed
   */
  public selectedDisplayText: string = "Please Select";

  /**
   * Search text
   */
  public searchText: string;

  /**
   * Observable for debouncing the search text change (300ms)
   */
  public searchTextChanged: Subject<string> = new Subject<string>();

  /**
   * variable to track if clicked inside or outside of component
   */
  public clickedInside: boolean = false;

  constructor() {
    this.multiple = false;
    this.searchTextChanged
      .debounceTime(300)
      .distinctUntilChanged()
      .subscribe((searchText) => {
        this.searchText = searchText;
        this.search();
      });
  }

  /**
   * click listener for host inside this component i.e
   * if many instances are there, this detects if clicked inside
   * this instance
   */
  @HostListener('click')
  public clickInsideComponent() {
    this.clickedInside = true;
  }

  /**
   * click handler on documnent to hide the open dropdown if clicked outside
   */
  @HostListener('document:click')
  public clickOutsideComponent() {
    if (!this.clickedInside) {
      this.toggleDropdown = false;
    }
    this.clickedInside = false;
  }

  /**
   * Component onInit
   */
  public ngOnInit() {
    if (typeof this.options !== "undefined" && Array.isArray(this.options)) {
      this.availableItems = JSON.parse(JSON.stringify(this.options));
      this.initDropdownValuesAndOptions();
    }
  }
  public ngOnChanges(changes: SimpleChanges) {
    if (changes.value && !changes.value.firstChange) {
      return;
    }
    this.selectedItems = [];
    this.searchText = null;
    this.availableItems = JSON.parse(JSON.stringify(this.options.sort()));
    this.initDropdownValuesAndOptions();
  }
  /**
   * When user changes search changes trigger the model change
   */
  public changed($event: any) {
    this.searchTextChanged.next($event);
  }

  /**
   * Deselct a selected item
   */
  public deselectItem(item: any, index: number, $event: Event) {
    this.selectedItems.splice(index, 1);
    if (!this.availableItems.includes(item)) {
      this.availableItems = this.options;
      // exclude selectedItems from availableItems
      this.availableItems = this.availableItems.filter((item: any) => !this.selectedItems.includes(item));
    }
    this.valueChanged($event);
  }

  /**
   * Select an item
   */
  public selectItem(item: string, index: number, $event: Event) {
    debugger
    if (!this.multiple) {
      if (this.selectedItems.length > 0) {
        this.availableItems.push(this.selectedItems[0]);
      }
      this.selectedItems = [];
      this.toggleDropdown = false;
    }
    this.availableItems.splice(index, 1);
    
    this.selectedItems.push(item);
    this.selectedItems.sort();
    // this.availableItems.sort();

    /*
      changes done to clear search text after selecting item
    */
   this.searchText="";
   this.search();
    this.valueChanged($event);
    
    
  }

  /**
   * When selected items changes trigger the chaange back to parent
   */
  public valueChanged($event: Event) {
    this.value = this.selectedItems;
    this.valueChange.emit(this.value);
    this.change.emit({ value: this.value });
    this.setSelectedDisplayText();
  }

  /**
   * Toggle the dropdownlist on/off
   */
  public toggleSelectDropdown($event: any) {
    this.toggleDropdown = !this.toggleDropdown;
  }

  /**
   * search for an item in the available items list
   */
  public search() {
    const searchResults: any = [];
    if (this.searchText === "") {
      this.availableItems = this.options;
      // exclude selectedItems from availableItems
      this.availableItems = this.availableItems.filter((item: any) => !this.selectedItems.includes(item));
      return;
    }
    for (const item of this.options) {
      if (typeof item !== "object") {
        if (item.indexOf(this.searchText) > -1) {
          searchResults.push(item);
        }
        continue;
      }
        if (item[this.config.displayKey].toString().toUpperCase().indexOf(this.searchText.toUpperCase()) > -1) {
          if (!searchResults.includes(item)) {
            // item is duplicated upon finding the same search text in the same object fields
            searchResults.push(item);
          }
      
      }
    }
    this.availableItems = searchResults;
    // exclude selectedItems from availableItems
    this.availableItems = this.availableItems.filter((item: any) => !this.selectedItems.includes(item));
  }

  /**
   * initialize the config and other properties
   */
  private initDropdownValuesAndOptions() {
    if (typeof this.config === "undefined") {
      this.config = {
        displayKey: "description"
      };
    }
    if (this.value !== "" && typeof this.value !== "undefined") {
      this.selectedItems = this.value;
      this.value.forEach((item: any) => {
        this.availableItems.splice(this.availableItems.indexOf(item), 1);
      });
      this.setSelectedDisplayText();
    }
  }

  /**
   * set the text to be displayed
   */
  private setSelectedDisplayText() {
    let text: string = this.selectedItems[0];
    if (typeof this.selectedItems[0] === "object") {
      text = this.selectedItems[0][this.config.displayKey];
    }
    if (this.multiple && this.selectedItems.length > 0) {
      this.selectedDisplayText = this.selectedItems.length === 1 ? text :
        text + ` + ${this.selectedItems.length - 1} more`;
    } else {
      this.selectedDisplayText = this.selectedItems.length === 0 ? "Please Select" : text;
    }
  }
  public clear(){
    debugger
    this.selectedItems=[];
    this.value = this.selectedItems;
     this.valueChange.emit(this.value);
     this.change.emit({ value: this.value });
    this.selectedDisplayText = "Please Select";
    this.searchText="";
    this.ngOnInit();
  }
}

**Comment by Navpreet7** [comment]
I am using it as the list of objects dropdown with multiple=false

**Comment by manishjanky** [comment]
so what i can make out is that the changes
``/*
  changes done to clear search text after selecting item
*/``
Are causing this. For this you can just set the search text to empty string. And call the search function it will automatically handle the available items. Also make sure you call the search function when you actually have searched and then selected an item.

Hope this helps.

**Comment by Navpreet7** [comment]
search text was remaining as it is after selecting the item and opening the dropdown again, that's why I had done this.
