### ISSUE TITLE
Only one item is displayed

### ISSUE THREAD

**Issue by bingika** [manishjanky/ngx-select-dropdown#102]
Only one item is listed. when i select the first item second item is shown. similarly the other items. can you please let me know if there is anything wrong in my configuration. I have tried giving limit to and height.

**Comment by Amr-Aly** [comment]
any updates about this issue?

**Comment by impace2019** [comment]
I am facing same issue . But insted of one i am getting two items. in my list ..  :) 

Is there any updates ?

**Comment by impace2019** [comment]
Solved the Issue.......!!


I was subscribing all objects in common functions. So first response gave me two options thats why all list showing first two options only.

Note - Common config object is used..


Previous Code -

 getAllDropDownData() {
    this.restDTService.getDroneServices().subscribe((data: any) => {
     // console.log(data);
      this.droneServicesList = data.data;
    });

    this.restDTService.getFrameTypes().subscribe((data: any) => {
     // console.log(data);
      this.frameTypeList = data.data;    
    });
  }


Updated Code -

 getDroneServices() {
    this.restDTService.getDroneServices().subscribe((data: any) => {
      // console.log(data);
      this.droneServicesList = data.data;
    });
  }
  getFrameTypes() {
    this.restDTService.getFrameTypes().subscribe((data: any) => {
      console.log(data);
      this.frameTypeList = data.data;
      console.log("Frames are " + this.frameTypeList.length())
    });
  }



Hope this will help you..... .


Happy Coding   ;)

**Comment by manishjanky** [comment]
@bingika @Amr-Aly @impace2019 can you guys please share you config and options array..
And if possible create a demo replicating the issue on Stackblitz.

**Comment by manishjanky** [comment]
Closing the issue as no input received as requested and inactivity.
