### ISSUE TITLE
error to migration angular 7

### ISSUE THREAD

**Issue by lorranpalmeira** [manishjanky/ngx-select-dropdown#104]
ERROR in : Template parse errors:
The pipe 'limitTo' could not be found ("h > 0" />
            <ul class="available-items">
                <li #availableOption *ngFor="let [ERROR ->]item of availableItems| filterBy: searchText : config.searchOnKey | limitTo : config.limitTo;let i = "): C:/Users/.../node_modules/ngx-select-dropdown/dist/components/ngx-select-dropdown-component/ngx-select-dropdown.component.d.ts.SelectDropDownComponent.html@20:49
The pipe 'filterBy' could not be found ("h > 0" />
            <ul class="available-items">
                <li #availableOption *ngFor="let [ERROR ->]item of availableItems| filterBy: searchText : config.searchOnKey | limitTo : config.limitTo;let i = "): C:/Users...../node_modules/ngx-select-dropdown/dist/components/ngx-select-dropdown-component/ngx-select-dropdown.component.d.ts.SelectDropDownComponent.html@20:49

**Comment by lorranpalmeira** [comment]
This Error occurs when I try  ng build --prod in angular 7

**Comment by manishjanky** [comment]
Please update to `v1.1.0`.

Let me know if you still face the issue.
