### ISSUE TITLE
default selected value with reactiveform

### ISSUE THREAD

**Issue by ermarkar** [manishjanky/ngx-select-dropdown#106]
This is what I am using

```
<ngx-select-dropdown  formControlName="departmentId"
                [config]="selectDropdownConfig" [options]="departmentList"></ngx-select-dropdown>

```
And my departmentId is a single key of type number (Expecting the same to be binded). Now when I submit the form (form.value), it shows the departmentId as the object. {id: "",description:""}. 

Should not it bind with the id only or it should as bind to which key?

And thanks for such a nice component.

**Comment by manishjanky** [comment]
The value will depend on the the options array passed.. So in your case i think the options object has two keys {id: "",description:""} that is why you got both in the value. The whole selected option is returned as value and not the single key.
If you need only one of the property you will have to extract it out..

Also if you can share the config and options i will be able to help you better..

**Comment by manishjanky** [comment]
Closing this issue as no further info provided..
