### ISSUE TITLE
form is submitting on clicking the ngx-select-dropdown? 

### ISSUE THREAD

**Issue by sukumardhoni** [manishjanky/ngx-select-dropdown#11]
i am using angular4 reactive forms module where i have used ngx-select-dropdown, where it is working unexpected behavior?

**Comment by manishjanky** [comment]
@sukumardhoni Thanks for reporting this.

Let me have a look and get back to you :)

**Comment by sreekm** [comment]
The 'ngx-dropdown-button' button doesn't have the type mentioned explicitly. So it is taking default value submit. The following fix in the file node_modules\ngx-select-dropdown\dist\components\ngx-select-dropdown-component\ngx-select-dropdown.component.js at line number 209 will work. But request manish to make this fix and release a new build 

 <button class=\"ngx-dropdown-button\" type=\"button\" (click)=\"toggleSelectDropdown($event)\">

**Comment by manishjanky** [comment]
@sreekm published with `v0.3.3`.
