### ISSUE TITLE
Single select drop down 'Options as array of Objects', On deselect item will append on end of list

### ISSUE THREAD

**Issue by khalidswipbox** [manishjanky/ngx-select-dropdown#110]
I have implemented drop down with single selection and pass option a array of objects but when I deselect item it disappear when I scroll down to the list then option appears on end of list (append on end of list not on its actual location), while same functionality working fine in 'Options as array of string' case on demo page.
  
This issue is also on demo page of 'Options as array of Objects'.

Steps to recreate issue.
Go to demo page 'Options as array of Objects'.
Select 'Amie Franklin'
Deselect 'Amie Franklin'
In search type 'ie'
'Amie Franklin' will appear in end of the list.

**Comment by lijo2** [comment]
Hi,
If you want the item always show in the same position, then you can provide a compare method in the config, as show below in typescript
  config = {
    displayKey: 'myDisplayKey',
    search: false,
    placeholder: 'Who completed the document',
    customComparator: (i1, i2)=>{
      console.log("i1: " + i1[this.config.displayKey]);
      console.log("i2: " + i2[this.config.displayKey]);
      let ret = i1[this.config.displayKey]<i2[this.config.displayKey];
      console.log( "result: " + ret);
      return ret? -1: 1;
    }
  };

html code:

<ngx-select-dropdown  [config]= "config"
[options]="MyObjectArray"  [multiple]="false"></ngx-select-dropdown>

Regards
Jonathan

**Comment by manishjanky** [comment]
@khalidswipbox what @lijo2 suggested is the solution to your problem. Specify a comparator function it will always maintain the sort order.
As in absence of comparator function it just use the default sort which never is as expected in case of array of objects.

**Comment by khalidswipbox** [comment]
@lijo2 Thanks its worked for me. Actually I am using this dropdown in multiple modules as multiple time whether we need to implement this comparator as individually at every module or is there any solution to implement that at its service level which auto implement on all modules where I have used this ?

Secondly @manishjanky  I have facing same issue https://github.com/manishjanky/ngx-select-dropdown/issues/84 (Keyboard navigation and selection does not work) You have any solution for that ?

**Comment by manishjanky** [comment]
@khalidswipbox  you can share the function across modules how you want to achieve it is up to you.. And for the #84 can you please share what exact error do you face.. As i checked and it works fine on my end. Also share the version you are using.

And will be great if you can create a demo replicating the issue on Stackblitz..
