### ISSUE TITLE
Keyboard navigation (up/down arrows) continues despite there are no more items and throws error

### ISSUE THREAD

**Issue by sebastian218** [manishjanky/ngx-select-dropdown#115]
Same error can bee seen on demo page.

ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at SelectDropDownComponent.push../node_modules/ngx-select-dropdown/dist/components/ngx-select-dropdown-component/ngx-select-dropdown.component.js.SelectDropDownComponent.handleKeyboardEvent

**Comment by manishjanky** [comment]
Please update to latest version `v1.1.0` this has been fixed
