### ISSUE TITLE
UTF-8 searching issue

### ISSUE THREAD

**Issue by hoanthan** [manishjanky/ngx-select-dropdown#116]
I have an array of options with utf-8 strings (Vietnamese). Ex: Cô tiên xanh, Cô tiên vàng,...
When I type "co tien xanh" or "co tien vang"
Expected: "Cô tiên xanh" or "Cô tiên vàng" is shown
Actual: No results found.
Please help me on this case

**Comment by manishjanky** [comment]
Hey There,
Way too sorry for not able to respond earlier.. Have been trying to figure out how to achieve this.. All I keep stumbling on is https://angular.io/guide/i18n and have not found any other solution..
I will keep looking and if I find anything will let you know.. I know its been a year.. So if you have found anything please do let me know..
