### ISSUE TITLE
How we can patch value ?

### ISSUE THREAD

**Issue by roshu26feb** [manishjanky/ngx-select-dropdown#118]
I have nested group form , I want to patch value to control like we add threw data[] in reactive form control
`componentListByType [ { 1 : 'component_id',  2 : 'component_id1'} ]`
`
(<FormArray>(<FormArray>this.addSystemVersionForm.controls['systemElements']).at(seIndex).get('components')).at(compIndex).get('componentName').patchValue(componentListByType);
`

``

**Comment by manishjanky** [comment]
This is how patchValue works 

```
formGroupName.patchValue({    
  formControlName: value
});  
```
