### ISSUE TITLE
custom CSS for dropdown scroll. #custom css

### ISSUE THREAD

**Issue by aniket-angularminds** [manishjanky/ngx-select-dropdown#119]
I want to add custom CSS for scroll so it can match my design.

**Comment by manishjanky** [comment]
@aniket-angularminds i dont have any css specific to the scroll bar applied to the component.. Did you try any custom scroll bar library.. Also if you use CSS please use it in the global style.css else it may not work.

**Comment by LucasJorgeHubert** [comment]
deep/.ngx-dropdown-container{
  .available-items{
    height: 180px;
    overflow-y: scroll;
  }
}

**Comment by manishjanky** [comment]
Closing this issue as a custom scroll can be added using any third party scroll library and adding it to this component will add to the complexity of the component and the idea is to keep it as simple as possible.
Also css can be overridden in the global stylesheet.
