### ISSUE TITLE
Show dropdown outside of container

### ISSUE THREAD

**Issue by Jennilein1991** [manishjanky/ngx-select-dropdown#12]
Hello :) ,

when i open my dropdown it looks like the following:

![image](https://user-images.githubusercontent.com/12052402/39942755-d23b35d6-5560-11e8-830c-569a3828f7eb.png)

Is it possible that the dropdown can be shown over this container? Now it is rendered in this container + a scrolling bar.

Jenni

**Comment by manishjanky** [comment]
Try giving your container a height say 100px and `overflow:visible`.  That should solve the problem.

**Comment by Jennilein1991** [comment]
`overflow:visible` works even without a fixed height :)
thanks!

**Comment by wbuback** [comment]
In my case, the parent container have `overflow: hidden` and I can't use `overflow: visible` by others factores.

ng-select have `appendTo` attribute for fix this problem.

Any solution?
Thanks!

**Comment by manishjanky** [comment]
@wbuback I'm working on this thing will update soon. Keep an eye.
