### ISSUE TITLE
How to Change the Selected item Background Color

### ISSUE THREAD

**Issue by Arunaliyanaarachchi** [manishjanky/ngx-select-dropdown#121]
I want to change the Selected Item Background color to Different color. try to change it using override global css. but it didn't change

.ngx-dropdown-button{
  background: red; /* bullet color */
}
![Image 9-7-19 at 1 55 PM](https://user-images.githubusercontent.com/25725120/64478485-36aafe00-d177-11e9-9081-f0baecdfecd1.jpg)

**Comment by Arunaliyanaarachchi** [comment]
@manishjanky

**Comment by LucasJorgeHubert** [comment]
`/deep/.ngx-dropdown-container{
  input{
    border-bottom-color: $orange-color !important;
  }
  outline: none;
  .available-items{
    height: 180px;
    overflow-y: scroll;
    li {
      outline: none;
      &:hover {
        background-color: #ff780171;
      }
    }
  }
  .selected-items {
    li{
      background-color: $orange-color !important;
      &:hover {
        background-color: red !important;
      }
    }
  }
}`

**Comment by manishjanky** [comment]
What is @LucasJorgeHubert  has suggested is correct. Also make sure you over ride this in you style.css file..
