### ISSUE TITLE
How do I clear search field after dropdown closes?

### ISSUE THREAD

**Issue by yuuuchu** [manishjanky/ngx-select-dropdown#125]
Hello,

I am trying to get the search field to auto clear after the dropdown closes and to NOT show the selected items at the top for single select. 

ts.
config = {
   search:  true, 
   clearSearchFilter: true,
   showSelectedItemsAtTop: false,
}

html.
<ngx-select-dropdown (change)="toggleSelection()" formControlName="items" [multiple]="false" [config]="config" [options]="customersList"></ngx-select-dropdown>

**Comment by manishjanky** [comment]
@yuuuchu  as of now i have not included this as part of the plugin let me see what best i can do.. Keep a watch

**Comment by yuuuchu** [comment]
Hi @manishjanky , 
Thank you for the reply. I actually found a workaround. 

For those coding with Angular (it will probably work in any language but I haven't tried....),
here it is: 

1) Name your ngx-select-dropdown and add the (open) function to it.

     ie: <ngx-select-dropdown **#dropdownName** [multiple]="false" [config]="config" [options]="myOptions" **(open)="dropdownName.searchText = null"**></ngx-select-dropdown>

Now every time the dropdown is opened, it will clear the search field. 
I hope this helps !! 
Cheers!

**Comment by yuuuchu** [comment]
@manishjanky  I am also going to mark this issue as closed. I don't think additional clear needs to be added into the plugin with this workaround. Maybe mention it in your description for the plugin?? 
But overall, thank you for making this plugin !! it's great to use :) !
