### ISSUE TITLE
Property 'searchTextChanged' is private and only accessible within class 'SelectDropDownComponent'.

### ISSUE THREAD

**Issue by lijo2** [manishjanky/ngx-select-dropdown#129]
After updating the version to 1.2.0, the build of our application failed to a typescript validation error:

ERROR in node_modules/ngx-select-dropdown/dist/components/ngx-select-dropdown-component/ngx-select-dropdown.component.d.ts.SelectDropDownComponent.html(10,43): Property 'searchTextChanged' is private and only accessible within class 'SelectDropDownComponent'.

The reason of the error is in ngx-select-dropdown.component.ts, the searchTextChanged method is private. But this is called from template code in ngx-select-dropdown.component.html. 

The proposed fix is set the searchTextChanged method to public.

As this is a regression issue, it needs to be fixed quickly.

Thanks
Jonathan

**Comment by lijo2** [comment]
Pull request
https://github.com/manishjanky/ngx-select-dropdown/pull/130
has been submitted for fixing this issue.

**Comment by manishjanky** [comment]
Closing this issues as this has been fixed.
