### ISSUE TITLE
Icomoon is overwriting my own style

### ISSUE THREAD

**Issue by Jennilein1991** [manishjanky/ngx-select-dropdown#13]
Hello :),
in my application i am currently using the following project:
https://github.com/kekeh/ngx-mydatepicker

When using this datepicker a datepicker is dynamically created with the class `icon-ngxmydpleft`. 
So when importing your style.css file the font-family will be overwritten with an !important tag:

![image](https://user-images.githubusercontent.com/12052402/40017640-40e2de48-57ba-11e8-9410-6f265338ac43.png)

So the icons in the datetimepicker are not shown. 
When i delete your css file, it works.

Any suggestions?
Since this datepicker is created dynamically i can not change this class.

Thanks :)
Jenni

**Comment by manishjanky** [comment]
Let me have a look. Will get back to you.

**Comment by manishjanky** [comment]
Hi Jenni,

I tried to use the dropdown with the date-picker you have referenced above it seems to work fine as the date-picker is dependent on bootstrap 3. When i tried it's working fine. All the icons are coming fine.

Can you please help me with the steps to reproduce the issue you are facing.

Manish

**Comment by manishjanky** [comment]
Hi,

Have published `v0.3.4` with the required changes. Please update and use.

Manish
