### ISSUE TITLE
Add Observable support

### ISSUE THREAD

**Issue by indraraj26** [manishjanky/ngx-select-dropdown#133]
Is there any plan to get value changes in ts without searchChange event because i want to apply rxjs operators.

Right now i am not getting output with valueChanges for formcontrol med.

Html
```
 <ngx-select-dropdown style="width:100%" [multiple]="false"
                                                [config]="selectConfig" [options]="medList" formControlName="med">
                                            </ngx-select-dropdown>
```

ts:
```

    this.medForm
      .get('med')
      .valueChanges.pipe(
        debounceTime(2000),
        distinctUntilChanged()
      )
      .subscribe(data => {
        console.log(data, 'med Id fired');
      });
```

**Comment by manishjanky** [comment]
@indraraj26 this should already work.. Let me see.. will get back to you..

**Comment by manishjanky** [comment]
@indraraj26 this is already working and no issue observed with subscribing to valueChanges event. Hence closing this.
