### ISSUE TITLE
Showing ID of item in drop down instead of name

### ISSUE THREAD

**Issue by vaishalikasar13** [manishjanky/ngx-select-dropdown#134]
Reactive formControlName showing ID of item in drop-down instead of name. Is there any way to show selected item in single select drop-down.

HTML
<ngx-select-dropdown  formControlName="id" [multiple]="false"  [config]="config" [options]="data" ></ngx-select-dropdown>

TS
 this.testForm.patchValue({
          id: this.testData.data.id
        });

![image](https://user-images.githubusercontent.com/33842217/68596539-6c46cd00-04c1-11ea-995e-9f424df1489f.png)

**Comment by manishjanky** [comment]
OK so if your options is an array of objects then your value also needs to be an object. As of now you set the value to `id` same is displayed. Instead do it this way
```
this.testForm.patchValue({
   id: this.testData.data
});
```

Where `this.testData.data`  is an object that is already part of the `options` array.
