### ISSUE TITLE
Angular 8 - Incompatible peer dependency

### ISSUE THREAD

**Issue by johnbenjaminphe** [manishjanky/ngx-select-dropdown#136]
Hi,

I had used ngx-select-dropdown in Angular 7 project, and now in the process of upgrading the project to Angular 8. But, I am getting the incompatible peer dependencies error.

Package "ngx-select-dropdown" has an incompatible peer dependency to "@angular/core" (requires "^4.0.0" (extended), would install "8.2.14").
                  
Package "ngx-select-dropdown" has an incompatible peer dependency to "@angular/common" (requires "^4.0.0" (extended), would install "8.2.14").
                  
Package "ngx-select-dropdown" has an incompatible peer dependency to "@angular/forms" (requires "^4.0.0" (extended), would install "8.2.14").

Whether I should wait for a new version of ngx-select-dropdown?

Thanks,
John Benjamin

**Comment by Toomavic** [comment]
Hello

I have the same warning

```shell
npm WARN ngx-select-dropdown@1.2.1 requires a peer of @angular/common@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-select-dropdown@1.2.1 requires a peer of @angular/core@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-select-dropdown@1.2.1 requires a peer of @angular/forms@^4.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by manishjanky** [comment]
@Toomavic / @johnbenjaminphe  have fixed this.. Will be releasing the patch by today or tomorrow..

**Comment by manishjanky** [comment]
Please update to latest version this is fixed.. Let me know if you still face issues..
