### ISSUE TITLE
ngx-select-search issue

### ISSUE THREAD

**Issue by yogita13364** [manishjanky/ngx-select-dropdown#137]
![ngx-select-search-issue](https://user-images.githubusercontent.com/13642875/70230150-b9932300-177d-11ea-869c-b77b6cde5511.PNG)

In search box, type a text that will match a single entry in dropdown, select that entry, 
message appears "No results found".
select it and click somewhere else. again click on select previously entered search term is still there with mesage "No results found".
Here the search term  is not getting cleared if we revisit the dropdown  also after selecting searched term mesage "No results found". appears
I have used this with angular 4

**Comment by manishjanky** [comment]
@yogita13364  may be in a day or two i will be releasing a patch with a functionality which will help you handle this.. Please keep a watch..

**Comment by manishjanky** [comment]
Please update to latest version, this is fixed and see readme for the changes related to this issue..

**Comment by yogita13364** [comment]
@manishjanky : With angular 4 i updated package.json with lates version as  "ngx-select-dropdown":"1.3.0" and then ran npm install. still i can see the mentioned issue is not completely fixed. PFB.
1. When multiple selection is false:
if u come back to the select dropdown: search is not getting cleared, also the message "No Results Found" appears
![Multiple-false](https://user-images.githubusercontent.com/13642875/71393782-322a2880-2634-11ea-87d5-6ff9f2b83b65.PNG)

 2. When multiple selection is true:
if u search a key type complete key name and then select it, once u select, below selected item message appears "No Results Found".
if u come back to this select, the search is getting cleared.
![Multiple-true](https://user-images.githubusercontent.com/13642875/71393664-a6b09780-2633-11ea-9bd8-d7b9d1dae102.PNG)

let me know if i can open this issue or need to create a new.

**Comment by manishjanky** [comment]
@yogita13364 i have added a new property in conrif `clearOnSelection` set this property to true and you wont face the issue. Let me know if that works.

**Comment by yogita13364** [comment]
@manishjanky :with clearOnSelection property set to true, it works perfectly for single select,
however for multiselect, now its clearing even after selecting a single value, and again we need to type search text to select second value for the same text. for multiselect, it should clear when we navigate back to the select. Also let me know, can i disable the text 'No Results Found', i tried making it blank or commenting that property but still it shows that text if clearOnSelection is false.
