### ISSUE TITLE
 functionality to select item inside list container from keyboard

### ISSUE THREAD

**Issue by Navpreet7** [manishjanky/ngx-select-dropdown#14]
can you provide the functionality of up & down arrows keys to highlight the items and enter key to select that item

**Comment by manishjanky** [comment]
Yes have that in mind. Keep a watch will add the functionality soon.

**Comment by Navpreet7** [comment]
Can you do it today , I need this functionality urgent

**Comment by manishjanky** [comment]
Can not commit to that. Working on this. Can expect this by weekend.

Also selecting items with enter and arrow key events will be working only for selecting an item. Deselecting won't be covered as of now.

**Comment by manishjanky** [comment]
please update to version `v0.4.0` and use.
