### ISSUE TITLE
Add formControlName - Support from using with Reactive Forms

### ISSUE THREAD

**Issue by Jennilein1991** [manishjanky/ngx-select-dropdown#15]
Hello :),
I'm using your dropdown menu in an reactive form in angular 5 and normally for input fields I need to add a formControlName to access the value and validate the input. Is there any possibility for that using your dropdown?

Jenni

**Comment by manishjanky** [comment]
Hi Jenni,

Right now no the component does not supports Reactive Forms. But yes in coming days it will for sure. By the time i can suggest you a workaround that will help you to use it with Reactive forms.

Keep a hidden input field in your Reactive form. Attach a change event listener to the dropdown and in the change event set the value of the hidden field using `pathValue()` . And you are good to go. So you add any validations required on the hidden field as that will be part of the Reactive form and will work as expected.
Please let me know if that helps. Can create a demo if you need.

And yes in future will add direct support for Reactive forms.

Manish

**Comment by Jennilein1991** [comment]
Okay thanks :)
When you added the support, please reply to this issue so i get informed 👍 

Jenni

**Comment by manishjanky** [comment]
Sure once the support is added will update you.

Manish

**Comment by manishjanky** [comment]
@thari119 sure will do

**Comment by sanath118** [comment]
Is the demo there yet?

**Comment by manishjanky** [comment]
@sanath118 sorry for the late response and delay in a demo. Will create in a day or two and will update you on the same.

**Comment by manishjanky** [comment]
@sanath118 below is a demo how you can use it with Reactive forms.

**form**
````
<form [formGroup]="formDemo">
   <ngx-select-dropdwon [options]="['1990','1991','1992','1993']" [(value)]="year" (change)="changeDropDownValue($event)"></sbe-select>
    <input type="hidden" formControlName="year" name="year">
</form>
````
**.ts file**
````
changeDropDownValue($event){
   this.formDemo.patchValue({year: $event})
}
````

Hope this helps. Let me know if you need any other help.

**Comment by manishjanky** [comment]
@Jennilein1991 @sanath118 @thari119 Reactive forms support have been added to the component. Please update to `v1.0.0` give it a try and let me know of any issues you face.

Closing this. Please open a new issue.

> Note: This version may have breaking changes. Please read the docs carefully

**Comment by sanath118** [comment]
> We are having a JSON
> [
> {
> "ID":1,
> "ASValue":"0"
> },
> {
> "ID":211,
> "ASValue":"8"
> },
> {
> "ID":311,
> "ASValue":"12"
> },
> {
> "ID":4,
> "ASValue":"17"
> },
> {
> "ID":5,
> "ASValue":"21"
> },
> ]
> 
> we need to sort the data based on ID.
> 
> If we are taking the full json into an array of ASData. and passing the ASData into the options.
> 
> And in config how we can sort the data based on ID.

Try using this.
[https://www.npmjs.com/package/sort-json-array]

**Comment by sanath118** [comment]
> We are having a JSON
> [
> {
> "ID":1,
> "ASValue":"0"
> },
> {
> "ID":211,
> "ASValue":"8"
> },
> {
> "ID":311,
> "ASValue":"12"
> },
> {
> "ID":4,
> "ASValue":"17"
> },
> {
> "ID":5,
> "ASValue":"21"
> },
> ]
> 
> we need to sort the data based on ID.
> 
> If we are taking the full json into an array of ASData. and passing the ASData into the options.
> 
> And in config how we can sort the data based on ID.

Try using this:
[NPM JSON SORT](https://www.npmjs.com/package/sort-json-array)

**Comment by koolkav1** [comment]
any progress on reactive forms?

**Comment by JorisPaul** [comment]
can you add reactiveForms support for multiselect?
