### ISSUE TITLE
reset the reactive form dropdown selected value is deleted form the option

### ISSUE THREAD

**Issue by amit62331** [manishjanky/ngx-select-dropdown#151]
when ngx-select-dropdown is used in reactive form and select any value.  after that reset the form. dropdown option value is deleted. suppose again i want select but value is not there.
Please find below code and link
https://stackblitz.com/edit/angular-mluc4h?file=src%2Fapp%2Fapp.component.ts

**Comment by manishjanky** [comment]
@amit62331 sorry for the delay.. I'm looking into this will update you soon.

**Comment by manishjanky** [comment]
@amit62331 please update to `v1.3.1` this is fixed.
