### ISSUE TITLE
Disable the deselection

### ISSUE THREAD

**Issue by JobyAntony** [manishjanky/ngx-select-dropdown#152]
Hi,
1. I want to disable the deselection link(link of the selected item). is there a way to do this?
Some of my dropdown controls needs to have behaviour, user should not deselect once they select a value. Do we have this behavior already available in the control? or else how to achieve this?
I am using the ver 1.3.0
and mustHaveAValue=true also not working.

2. Search is not considering the selected item, if we search for selected item, 'Item not found' message is displaying, My requirement is in this case we should not show the message.

**Comment by manishjanky** [comment]
@JobyAntony yes there is a way where you can disbale the dropdown itself using the ``[disbaled]`` property and when you want the user to re-select a value enable the dropdown again. For required validation and others you will have to do that in your code.
