### ISSUE TITLE
Search input clears automatically when options changes

### ISSUE THREAD

**Issue by marcinsikorski** [manishjanky/ngx-select-dropdown#155]
I would like to keep search value visible after new values arrival.

I connected that component with ngx-infinite-scroll to make dropdown paginated and I use search input to query new values according to its value. But new values arrival (change of options) clears search input.

Edit: Search value is cleared when options list is changed to empty (temporary until new values are loaded).

**Comment by manishjanky** [comment]
Can you please share more details about version you are using and may be please create a demo replicating the issue on stackblitz. 
Also there is a config property `clearOnSelection` please make sure it is set to false.

**Comment by alex250195** [comment]
I've same problem. 

On my component I use a "searchChange" event to call a method and into this method I call an api to bring new itens to show on my dropdown list. And as soon as I call this api my input text on search field is automatically clears.

Follow my code:

HTML:
`<ngx-select-dropdown formControlName='movementType' [multiple]="true" [config]="selectConfig" [options]="results.movementType" (searchChange)="recoverMovementTypes($event)" (open)="recoverMovementTypes()"></ngx-select-dropdown>`

SelectConfig:
```
public selectConfig = {
    displayKey: 'text',
    search: true,
    height: 'auto',
    placeholder: ' ',
    customComparator: ()=>{},
    moreText: ' ',
    noResultsFound: 'Nenhum registro encontrado',
    searchPlaceholder:' ',
    searchOnKey: ' ',
    clearOnSelection: false
  };
```

Method called on searchChange event:
```
public recoverMovementTypes(word: string = undefined) {
    this.apiRequest.get('MovementType').subscribe((result: Array<MovementTypeModel>) => {
      const resultMap: Array<Select2OptionData> = this.mapFiltersObjects(result, 'code', 'description');

      if(word) this.results.movementType = resultMap.filter(f => f.text.includes(word));
      else this.results.movementType = resultMap;
    });
  }
```

**Comment by RsknCankov** [comment]
Hey guys, 
I faced same issue, after checking source of the library I think this line is causing the problem:
[https://github.com/manishjanky/ngx-select-dropdown/blob/f034a42c2ed5b364c69221d90a550bd5453fdf62/src/components/ngx-select-dropdown-component/ngx-select-dropdown.component.ts#L325](url)

**Comment by manishjanky** [comment]
Update to latest version
