### ISSUE TITLE
Tab order Issue

### ISSUE THREAD

**Issue by JobyAntony** [manishjanky/ngx-select-dropdown#158]
Tab index is not working as expected, my requirement is to navigate controls using Tab key, This key should not open the drop down. if the user press any other key or click on the drop down, drop down should open. 
could you please help it is an urgent requirement. Thanks in advance.

**Comment by manishjanky** [comment]
@JobyAntony let me have a look. Will do what i can..

**Comment by manishjanky** [comment]
Please update to latest version. This is fixed..
