### ISSUE TITLE
Setting a value which is not available in options

### ISSUE THREAD

**Issue by raju1014** [manishjanky/ngx-select-dropdown#159]
When i'm setting a value to drown-down it updating. But if i'm setting a value which is not there in option also it is setting.. Can yo please help out on this.

**Comment by manishjanky** [comment]
@raju1014 let me check. Will update you soon.

**Comment by raju1014** [comment]
Hey any Updates...?

**Comment by manishjanky** [comment]
@raju1014 sorry for the delay.. have been stuck with work.. will see if i can find time to see to it this weekend.. Also if you have a solution i'm happy to accept a PR

**Comment by manishjanky** [comment]
@raju1014 after due thought and consideration I think I will keep it that way.. Its for the developer using the component to make sure nothing of that sort happens.. Adding too much of check will add to the complexity of the component and un-necessary overhead.. I hope you understand..
