### ISSUE TITLE
After selecting first item the last item is deleted

### ISSUE THREAD

**Issue by Jennilein1991** [manishjanky/ngx-select-dropdown#16]
Hello :)
this is a similar issue as the solved issue with the title "Last option will be deleted when selecting a random option".

Now after updated to version 0.3.4 of your dropdown, the following bug occurs:
This is how the dropdown looks like:

![image](https://user-images.githubusercontent.com/12052402/40203744-79e22794-5a26-11e8-9eb7-6aab9c7791f3.png)

After selecting "Female":

![image](https://user-images.githubusercontent.com/12052402/40203769-93f5a1b0-5a26-11e8-95a9-018558143c55.png)

I also can not search for "Male" anymore.

Jenni

**Comment by manishjanky** [comment]
Sorry for this.

Fixed and published with `v0.3.5`
