### ISSUE TITLE
[bug] Remove item is getting added at last

### ISSUE THREAD

**Issue by indraraj26** [manishjanky/ngx-select-dropdown#160]
Bug: Select any element from dropdown when you remove from selected that will add it last, Not on same position from where we have selected. Suppose we have selected first element from dropdown then unselect it will add that item to last.

pic: 
1.
![image](https://user-images.githubusercontent.com/23274631/74635801-c0321380-518c-11ea-9c39-675b495451f6.png)
2. 
![image](https://user-images.githubusercontent.com/23274631/74635836-ce802f80-518c-11ea-858e-e7ba93100afe.png)
3. 
![image](https://user-images.githubusercontent.com/23274631/74635890-e952a400-518c-11ea-92a3-1754e5221ea3.png)

To reproduce: 
Stackblitz: https://stackblitz.com/edit/angular-ragp3h?file=src%2Fapp%2Fapp.component.html

**Comment by manishjanky** [comment]
@indraraj26 this is not a bug in your config you can actually control this by passing the `customComparator` like below as this is used to sort the items.. Read the docs for more info..
```
customComparator: (a,b) => { return a > b},
```

**Comment by indraraj26** [comment]
I have added but still it is adding at the end of list not where it was.
Tried both
```
customComparator: (a,b) => { 
    return a.name > b.name
    }
```
```
customComparator: (a,b) => { 
    return a > b
    }
```
Link: https://stackblitz.com/edit/angular-ragp3h?file=src%2Fapp%2Fapp.component.ts
