### ISSUE TITLE
How can I add custom HTML template for drop down item

### ISSUE THREAD

**Issue by ermarkar** [manishjanky/ngx-select-dropdown#162]

**Comment by manishjanky** [comment]
This is functionality is not there as of now, but is on the list and will be incorporated soon.. please keep a watch..

**Comment by Dacili** [comment]
Is this implemented? 
Is there a possibility to add a tooltip on dropdown options?

**Comment by vasnakos** [comment]
Any update on this? I would like to have the items translatable.

**Comment by manishjanky** [comment]
Please upgrade to latest version `v3.3.0`
