### ISSUE TITLE
different style for placeholder text

### ISSUE THREAD

**Issue by maloneyg** [manishjanky/ngx-select-dropdown#167]
We would like to be able to apply a different style to the placeholder text than we do to the text for the selected items.  Perhaps this could be achieved by applying a different class to the `span` element.

**Comment by manishjanky** [comment]
@maloneyg  you can always override the styles in your global stylesheet

**Comment by SandeepBalachandran** [comment]
Hi @manishjanky , How do i override the styles in global stylesheet? Confusions because both placeholder and selected value comes inside a span and there is no classes changing upon selecting or deselecting values? So having confustions for distinguishing these 2 events

**Comment by PriyanshDwivedi** [comment]
any update on this one? Really destroys the aesthetics of the form!

**Comment by SandeepBalachandran** [comment]
I will explain what i have done in my scenario which was  the case of form arrays. 
1. Once the value is selected , the corresponding form array value will be set.
2.  It is possible to distinguish between empty span and selected span by using a [ngClass] in <ngx-select-dropdown> once value in the array set.
For example ,

` .selected span { color:black }    `

`[ngClass]="{'selected':data.value.alternateskill?.id}"  `

I was checking whether the id is set or not . Id will be set once value is selected.
I think the same can be applied to ngModel as well.

**Comment by PriyanshDwivedi** [comment]
This

> I will explain what i have done in my scenario which was the case of form arrays.
> 
> 1. Once the value is selected , the corresponding form array value will be set.
> 2. It is possible to distinguish between empty span and selected span by using a [ngClass] in  once value in the array set.
>    For example ,
> 
> `.selected span { color:black } `
> 
> `[ngClass]="{'selected':data.value.alternateskill?.id}" `
> 
> I was checking whether the id is set or not . Id will be set once value is selected.
> I think the same can be applied to ngModel as well.

This is brilliant. Thanks a ton for this hack. Haven't tried it yet but will definitely work.
