### ISSUE TITLE
Folder Missing

### ISSUE THREAD

**Issue by rajatgangwani33** [manishjanky/ngx-select-dropdown#168]
In new update we are not abl to get the **asset** folder which result in fail in deployment. A Folder for assets is missing .Kindly resolve this.

**Comment by manishjanky** [comment]
@rajatgangwani33 the assets folder no longer is part of the library.. Please go through the docs.. you don't have yo include the style.css in angular.json/angular-cli.json

**Comment by rajatgangwani33** [comment]
Ok thanks for the clarification.
