### ISSUE TITLE
Verticle Height is not changing

### ISSUE THREAD

**Issue by bopcheshailesh** [manishjanky/ngx-select-dropdown#169]
Hi have setted the verticle height to '5px' it does work. Im using angular 9, ngx-select-dropdown 1.4.0.
Please help me out in this. I have a dropdown which can have upto 20-30 items .
 
One more query.
If i want to fix the component width to its largest character value, is it possible?

**Comment by manishjanky** [comment]
@bopcheshailesh  i think i m not able to understand your query completely.. 
But if you set the height to some fixed value it will take that and if there is a overflow situation the a scrollbar will appear.. else the list will be as long as the number of items..

And for the width you can control the width as per your need.. Just wrap the component in a div and set whatever width you want to the div the component will take the available width..
