### ISSUE TITLE
Be able to change the style

### ISSUE THREAD

**Issue by leandrocervelin** [manishjanky/ngx-select-dropdown#17]
Hi,  @manishjanky . 
First of all, thanks for this nice feature you developed. I am using bootstrap and I would like to change the css of the dropdown to approximate it from my others components. What do you think about turn it able  to set up the css, as a cusstomized way? 
Is it possible set the default Placeholder instead "select"? Have you ever tried set the default selection after deselect all?

**Comment by manishjanky** [comment]
I think you can still override css. Just write your rules in style.css i.e the global css file for your angular app. But still let me have a look and get back to you.

**Comment by manishjanky** [comment]
@leandrocervelin To achieve what you want is simple. As i stated earlier you can override the components style in the global `style.css` or `style.scss` depensd on are you using sass or not. Just use the `!importnat` specifier with the values. Like below
````
.ngx-dropdown-button {
    background: skyblue !important;
    color: white !important;
}
````

The above piece of code will change the background color to skyblue and text color to white.

Hope this helps. Please let me know if you face any issue.
Closing the issue.

**Comment by lruiz-invidgroup** [comment]
The word "Select" can be changed by parameter or directly in the file?

**Comment by manishjanky** [comment]
@leandrocervelin Right now only in the code. But i would accept having it configurable is a good option.
Will for sure consider that and implement in coming version.

**Comment by manishjanky** [comment]
@charan-r please update to`v0.6.0`. The placeholder has been made configurable.

**Comment by kevpeisker** [comment]
Is there a way to conditionally override the style. I need to make the border red when a flag in my component is set indicating that the user attempted to submit the form? Also, why can we only override the styles in the global styles.css?

**Comment by Armadar** [comment]
> Is there a way to conditionally override the style? I need to make the border red when a flag in my component is set indicating that the user attempted to submit the form. Also, why can we only override the styles in the global styles.css?

hope it will be helpful:

Add these classes to the main css:

.border-green {
    border: 1px solid green !important;
}
.border-red {
    border: 1px solid red !important;
}

work in the (change) Event TS :

onSelectedCategory(event) {
    var control = document.getElementById('category').children[0].children[0];
    if (event.value != undefined) {
      this.selectedCategory = event.value.id;
      control.classList.remove('border-red');
      control.classList.add('border-green');
    } else {
      this.selectedCategory = 0;
      control.classList.remove('border-green');
      control.classList.add('border-red');
    }
  }

**Comment by Vigneshhackiee** [comment]
how to validate and highlight red color show
 ngx-select-dropdown  in angular
