### ISSUE TITLE
[bug][reopen] Remove item is getting added at last

### ISSUE THREAD

**Issue by indraraj26** [manishjanky/ngx-select-dropdown#170]
Bug: Select any element from dropdown when you remove from selected that will add it last, Not on same position from where we have selected. Suppose we have selected first element from dropdown then unselect it will add that item to last.

> @indraraj26 this is not a bug in your config you can actually control this by passing the `customComparator` like below as this is used to sort the items.. Read the docs for more info..
> 
> ```
> customComparator: (a,b) => { return a > b},
> ```

I have added but still it is adding at the end of list not where it was.
Tried both
```
customComparator: (a,b) => { 
    return a.name > b.name
    }
```
```
customComparator: (a,b) => { 
    return a > b
    }
```
Link: https://stackblitz.com/edit/angular-ragp3h?file=src%2Fapp%2Fapp.component.ts

https://github.com/manishjanky/ngx-select-dropdown/issues/160

**Comment by manishjanky** [comment]
@indraraj26 sorry for the delay in response..

And to your issue.. Please have a look at the stackblitz you have created it works perfectly fine..
1.Select Blue
2.Select Tobby
3.Deselect Blue

Blue gets added as the first element in the available options so its no getting added to the end of the list the sort function comes in to play and works as expected. Please re-check your implementation you must be missing somehthing if that's not how its behaving for you.

**Comment by indraraj26** [comment]
Hi @manishjanky , 

Reproduce: 
1. Select indra.
2. deselect indra

Now indra will be in last (It should be at its original position which was first)

Link: https://stackblitz.com/edit/angular-ragp3h?file=src%2Fapp%2Fapp.component.ts

**Comment by indraraj26** [comment]
Even other playground has same issue : 
Item#1 was first item in list.

pre : 
![image](https://user-images.githubusercontent.com/23274631/78130925-ced04380-7437-11ea-9394-4e13054d3c0b.png)


post: 
![image](https://user-images.githubusercontent.com/23274631/78130948-da236f00-7437-11ea-9a5d-4054df34e5d1.png)

Link : https://stackblitz.com/edit/angular-b9pl7t?file=src%2Fapp%2Fapp.component.ts

**Comment by manishjanky** [comment]
OK let me cross check..

**Comment by indraraj26** [comment]
if this fix in this commit please publish new build to npm. let me know when are you going to publish it, I will test and review it.
Thank you.

**Comment by manishjanky** [comment]
@indraraj26 i'm on it give me some time.. Couple of other stuff to sort out

**Comment by manishjanky** [comment]
Update to latest version

**Comment by indraraj26** [comment]
I will test tomorrow and will get back to you.

**Comment by indraraj26** [comment]
Update to 1.4.2

Still same
reproduction :  https://stackblitz.com/edit/angular-8s89ob?file=src%2Fapp%2Fapp.component.ts


> Even other playground has same issue :
> Item#1 was first item in list.
> 
> pre :
> ![image](https://user-images.githubusercontent.com/23274631/78130925-ced04380-7437-11ea-9394-4e13054d3c0b.png)
> 
> post:
> ![image](https://user-images.githubusercontent.com/23274631/78130948-da236f00-7437-11ea-9a5d-4054df34e5d1.png)
> 
>

Reproduce:

Select indra.
deselect indra
Now indra will be in last (It should be at its original position which was first)

Link: https://stackblitz.com/edit/angular-ragp3h?file=src%2Fapp%2Fapp.component.html

**Comment by indraraj26** [comment]
It would be great if you can re-open this issue

**Comment by manishjanky** [comment]
change your comparator to below
```
  customComparator: (a,b) => { 
    return a.name > b.name? 1: -1;
    }
```

According to the official docs the comparator function must return -1 or 1.

**Comment by indraraj26** [comment]
Thank you @manishjanky It works as expected :)
