### ISSUE TITLE
(change) event is colliding with angular input event with the same name

### ISSUE THREAD

**Issue by JuliusSkrisa** [manishjanky/ngx-select-dropdown#171]
Since "change" event is implemented for triggering from within the component, and component is also implementing ControlValueAccessor interface to make it custom angular template driven form inputs.  
There are 2 change events present in this component which are colliding. Sometimes "change" event can be called without expected value (in form of {value: 'value'}), but just with Event object. of the angular change event implementation for inputs.

In my case this is causing "change" event being triggered when changeDetection is triggered when focusing out/ closing dropdown with Event object. 

Solution for this is easy just to rename "change" event to something else.

**Comment by manishjanky** [comment]
@JuliusSkrisa can you please create a demo or something show the issue you are facing.. I tried changing the change event name to something else and listen to angular's change event, it did not trigger at all.. If you can create a stackblitz show the issue you face may be i will be able to figure it out.

**Comment by Krismix1** [comment]
I think I encountered the same problem. I put together a [demo](https://stackblitz.com/edit/angular-vnhmf2) project.

How to trigger the collision:
1. Type a letter in the search bar, e.g. `e`.
2. Select any of the dropdown items.

In the console, you should see 2 lines being printed:
Line 1:
```text
item Event {isTrusted: true} dataModel undefined
```
Line 2:
```
item {value: Array[1]} dataModel ["hello"]
```

I hope this helps.

**Comment by JuliusSkrisa** [comment]
@manishjanky 
Yes exactly what @Krismix1 mentioned, 
sorry for not adding steps to reproduce myself, didnt have much time.

Also when you just type something into the search field and then loose focus. There will be only Angular change event triggered. Which is where my code was failing trying to get the value from that Event object and reseting my internal application state value for this field, because there was no value property present.

**Comment by manishjanky** [comment]
@Krismix1 / @JuliusSkrisa  this has been fixed, please update to latest version. Now only one change event is emitted. Also if you want  to lookout for the search change event use `searchChange` . Read more in docs.
