### ISSUE TITLE
Not able to fire changeEvent on setting the value to the dropdown

### ISSUE THREAD

**Issue by raju1014** [manishjanky/ngx-select-dropdown#172]
Hi,
I'm setting values to the dropdown with reactive forms..
When a value is set(form.setValue({})), the change event is not firing.. I again need to specifically call the change event.

Where has the same is working when I'm selecting a value from the dropdown.

Can you please help me out on this.

Thanks,
Raju

**Comment by manishjanky** [comment]
@raju1014 So this is a issue i have observed with most of the controls if you google it you will find lot of threads complaining about the same... The change event does gets triggered but not the usual way.. The solution to you problem is that you will have to subscribe to the changes of the form or control like this..

```
    this.formGroup.get('controlName').valueChanges.subscribe((changes) => {
      console.log(changes);
    });
```

So whenever you need to listen to the change event do it this way. 
Now if you change the value using below piece of code it works perfectly fine..
` this.formGroup.get('controlName').setValue({id: 1});`

This will solve your problem..
