### ISSUE TITLE
Angular 9 compatibility Error: Failed to compile entry-point ngx-select-dropdown (module as esm5) due to compilation errors

### ISSUE THREAD

**Issue by ahmedsherifm** [manishjanky/ngx-select-dropdown#173]
I was trying to upgrade my project from Angular 8 to Angular 9, So after the upgrade, I tried to run 
**`ng serve`**
I got this error:
![image](https://user-images.githubusercontent.com/11089826/79361736-ffd76a80-7f45-11ea-9c6b-cf8b14e95122.png)

.
.
Compiling ngx-select-dropdown : module as esm5
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Error: Failed to compile entry-point ngx-select-dropdown (module as esm5) due to compilation errors:
node_modules/@angular/forms/forms.d.ts:2574:22 - error NG6002: Appears in the NgModule.imports of SelectDropDownModule, but could
not be resolved to an NgModule class.

This likely means that the library (@angular/forms) which declares FormsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with
the library's authors to see if the library is expected to be compatible with Ivy.

2574 export declare class FormsModule {
                          ~~~~~~~~~~~
.
.

---------
Environment versions:
Node: 12.16.2
Angular CLI: 9.1.1
ngx-select-dropdown: I tried with 1.3.1 and 1.4.2

**Comment by manishjanky** [comment]
OK so I tried this with angular 9 and it works fine. May be you need check if @angular/forms is properly installed or not..May be uninstall nix-select-dropdown and the install @angular/forms and re-install nix-select-dropdown..
If you still do no come right let me know I will see what I can do..
