### ISSUE TITLE
Focus on search input and write something and press enter, it is submitting form.

### ISSUE THREAD

**Issue by Nouman24** [manishjanky/ngx-select-dropdown#174]
Write something in the search input and press enter it will close dropdown and submit your form. 
![image](https://user-images.githubusercontent.com/18117734/79461967-514c2c00-8010-11ea-9e0e-d0391d566cd4.png)

**Comment by manishjanky** [comment]
OK will see what I can do to avert such behaviour but. There might be other reason for this being happening.. Please do cross check your form and how its being submitted..

**Comment by Nouman24** [comment]
@manishjanky  yeah there was not an issue with my form but in angular 8 I have used ngSubmit and it fixed.
