### ISSUE TITLE
Clear input using external button e.g Reset button.

### ISSUE THREAD

**Issue by aditya777hp** [manishjanky/ngx-select-dropdown#177]
I want to clear the selection using an external button e.g reset.

**Comment by manishjanky** [comment]
You can still do that.. If you are using this with reactive forms the .setValue() or patchValue() can do that for you. If you are using template driven form then change the variable used with ngModel can do that. You just need handle this on the button change.

**Comment by adisco4420** [comment]
I tried using both .setValue('') and .patchValue('') the form value was reset but the selected value still persist on the dropdown.

**Comment by ameydagariainfobeans** [comment]
@manishjanky  tried using setValue And PatchValue its not clearing selected value.

**Comment by yoedusvany** [comment]
Any solution for this?

**Comment by a30001735** [comment]
**Used to work**
Setting null with patch or setvalue used to work like this  `this.formGroup.patchValue({ controlName: null});` with angular 7 and ngx-select version 1.3.
But it stopped working when we moved to angular 10 with ngx-select version 1.4.3.
reset() also don't seems to deselect anymore.  BTW, I am using it within a child component, but should be same I assume.

**Work around**
The following seems to work now. (Angular 10 with ngx-select version 1.4.3)
`this.formGroup.controls['controlName'].patchValue([]);`
or 
`this.baseFormGroup.patchValue({ vintage: [] });`
picked from here - https://github.com/manishjanky/ngx-select-dropdown/issues/181

**Comment by yoedusvany** [comment]
Thanks, I tested this option that runs ok for me. I'm using angular 8

this.formGroup.controls['controlName'].patchValue([]);

**Comment by manishjanky** [comment]
Let me have a look at this guys. Might be something with the angular upgrades.

**Comment by ameydagariainfobeans** [comment]
@manishjanky  tried using this.formgroup.get('control').patchValue([]); still not working with angular 9 and ngx-select-version 1.4.2 any work around for that ?

**Comment by yoedusvany** [comment]
Hi guys, again here. Any way yo reset ir using ngModel field?

**Comment by manishjanky** [comment]
this is sorted guys, please update to latest version. Let me know if you face any issues.
