### ISSUE TITLE
Search Case Sensitive

### ISSUE THREAD

**Issue by MohsinBashir** [manishjanky/ngx-select-dropdown#18]
Search is case sensitive. Is there any option to customize it. like treat "CODE" and 'code' as same.

**Comment by manishjanky** [comment]
@MohsinBashir  Please update to `v0.4.0` have made search case insensitive in this version.

Manish

**Comment by niteshgaba** [comment]
Hi,

The issue still exists with v.0.4.1. Could you please have a look one again?

**Comment by manishjanky** [comment]
@niteshgaba First of all sorry for the late response. 

`v0.4.1` is having case insensitive search. Now uppercase and lowercase won't matter if the characters match they will be part of the search.

**Comment by kumaresank** [comment]
Still search is case sensitive only with version 0.4.1. Please check it once

**Comment by manishjanky** [comment]
@kumaresank  will have a look and update soon.

**Comment by manishjanky** [comment]
Please update to `v0.4.2`
