### ISSUE TITLE
Dropdown doesn't get closed on clicking tab

### ISSUE THREAD

**Issue by Chetna124** [manishjanky/ngx-select-dropdown#180]
Hi, 
I have used this in my project but facing  a major issue. I have many form fields and using reactive form. ("ngx-select-dropdown": "^1.4.2",angular 8)
When I use tab and reach this element and press tab again, the dropdown opens, then another tab takes me to search option. When i click tab again, it takes me to the next element but  dropdown remains open. I have tried to capture (close) event, but doesn't get fired when I click tab. When I tab again, then it closes. (screenshot attached).
![error](https://user-images.githubusercontent.com/22514356/83454121-527ad080-a479-11ea-8313-ece0e279a52d.PNG)

Second issue i am facing,
I am using single select([multiple]="false"), so i don't want to show the selected items. I had set the limit to 0 but still it shows the single element i have selected. Is there any configuration for the same?

**Comment by manishjanky** [comment]
Let me have a look at the Tab issue..
And for the other issues, there is  no such config. But you can use below css for that.
```
.selected-items{
   display: none !important;
}
```

This will hide the selected items list. Keep this in your global style.css

**Comment by manishjanky** [comment]
Closing this as there is already a issue raised for the TabOrder #158 .. I will see if i can fix this soon enough.

**Comment by Chetna124** [comment]
thankyou, please try to provide with a fix asap. Urgently required.

**Comment by Chetna124** [comment]
Please tell me one more thing, when we click on this control, popup opens,
when we click outside without selection or doing anthing, popup closes but the touch is still false. I am using reactive forms
