### ISSUE TITLE
Reactive form reset not working and control touch true even after touching the control

### ISSUE THREAD

**Issue by Chetna124** [manishjanky/ngx-select-dropdown#181]
("ngx-select-dropdown": "^1.4.2",angular 8)
**Issue 1 :** 
When we click on this control, popup opens, when we click outside without selection or doing anything, popup closes but the touch is still false.
So, my error required error doesn't gets fired.

**Issue 2:**
I want to reset this control, 
When i reset this.myForm.controls[dropdownfield].reset();
This has reset my control value, but the previous selected value still shows up on the dropdown.
When i try to figure it out, I could concluded selectedItems value has the value even on reseting the control.
I am unable to clear selectedItems even after reseting the control. I have event tried with Viewchild and making selectedItems = [];

P.S I have read the closed issues, but all gives solution for template driven form.

**Comment by amahajan02** [comment]
Even I was facing same issue with reactive forms. For me setting it to empty array inside patchValue worked.
Try this:
this.myForm.controls[dropdownfield].patchValue({selectedItems: []});

**Comment by Chetna124** [comment]
> this.myForm.controls[dropdownfield].patchValue({selectedItems: []}); 
@amahajan02 This worked well for me . Thankyou.

Please give some idea about the #issue1
When we click on this control, popup opens, when we click outside without selection or doing anything, popup closes but the touch is still false.
So, my error required error doesn't gets fired.
Error comes when i submit the form, that's not the issue, but not after i touch it and don't select the value.

**Comment by Chetna124** [comment]
@amahajan02  this.employment.controls[dropdownfield].patchValue([]); 
this worked for me. Thankyou for the idea.

**Comment by manishjanky** [comment]
@Chetna124  let me see what I can do for the touched issue..

**Comment by manishjanky** [comment]
@Chetna124 just stumbled upon something on the angular repository itself. This is an open issue with angular. So there's not much I can do for now..

https://github.com/angular/angular/issues/10887

**Comment by Chetna124** [comment]
@manishjanky  okay, please see tab index issue, with that i may be able to fix this by using close event.

**Comment by manishjanky** [comment]
Yeah, by listening to the `close` event you can use the markAsTouched() function to set the touched state.
Looking into the tab index one. Closing this one
