### ISSUE TITLE
dropdown still remains open when opened through keyboard( taken latest)

### ISSUE THREAD

**Issue by Chetna124** [manishjanky/ngx-select-dropdown#184]
#158 
I was closely following this issue, as i had raised the similar issue. 
Steps:
Reach the dropdown through tab. 
Open dropdown by pressing enter.
Now tab again, it moves to the next control without closing the dropdown.
(Screenshot attached)
![error_occu](https://user-images.githubusercontent.com/22514356/84747375-c918e180-afd4-11ea-9b20-13b1b054537f.PNG)

"ngx-select-dropdown": "^1.4.3",  // taken update after you fixed tab index issue
angular 8

**Comment by manishjanky** [comment]
Let me see what did i miss..

**Comment by manishjanky** [comment]
please update to latest version
