### ISSUE TITLE
Cannot find the CSS style in node modules directory

### ISSUE THREAD

**Issue by Suresh643** [manishjanky/ngx-select-dropdown#187]
The mentioned CSS file in 'angular.json' doesn't exist in node modules directory. i.e "../node_modules/ngx-select-dropdown/dist/assets/style.css"

**Comment by ahmedsherifm** [comment]
same here
using Angular 9.1.9
node 12.18.2
ngx-select-dropdown 1.3.1 - and tried it with 1.4.3 also

![image](https://user-images.githubusercontent.com/11089826/87443781-3a5cac00-c5f6-11ea-959c-50f9e08f13d3.png)

**Comment by ahmedsherifm** [comment]
@manishjanky

**Comment by manishjanky** [comment]
Yes its is not part of the component any more. Please read docs it mentioned there since which version the same was removed and what you need to do if you are using the respective version with/without the style.css.
