### ISSUE TITLE
Design issue, Select box text lenght

### ISSUE THREAD

**Issue by Prashanthmn166** [manishjanky/ngx-select-dropdown#189]
If the length of the text inside select box is exceeding select box length, downward arrow is moving to the next line
![selectbox issue](https://user-images.githubusercontent.com/44411303/87747160-1bd1fd00-c810-11ea-9bd5-3fa4a09beaa4.PNG)

**Comment by manishjanky** [comment]
Thanks. Will fix this.

**Comment by manishjanky** [comment]
This is fixed. Please let me know if you still face this issues.
