### ISSUE TITLE
Unable to bind value using ngmodel

### ISSUE THREAD

**Issue by manikantavarmaN** [manishjanky/ngx-select-dropdown#190]
Hi,
I am trying to bind an item to ng select dropdown using ngmodel . It was successfully bound for the first time . But when I try next time to assign new value it is not changing?

Code:
 <ngx-select-dropdown [(ngModel)] ="userSelectedCompany"  (change)="selectRootCompany($event.value)" [config]="ngxconfig" [options]="userCompanies" class="text-overflow-button"></ngx-select-dropdown>

  userSelectedCompany: any ;

**Comment by manishjanky** [comment]
Can you please create a demo replicating the issue? Will be able to help better.
