### ISSUE TITLE
selected value is not getting clear . duplicate items are displaying in list 

### ISSUE THREAD

**Issue by ameydagariainfobeans** [manishjanky/ngx-select-dropdown#192]
i have used reactive form and binded formcontrol with ngx-selected-dropdown 

**example :-**  <ngx-select-dropdown [options]="testDropdown" [config]="config"> </ngx-select=dropdown>

in ts file on oninit click i am  calling an api and filling the options . like this                                                                         this.testDropdown = [...this.testDropdown,...this.tempArray ]  after that the drop down is filled and user selects a value and it shows on selected . after that on a button click i am calling api again and refilling the  this.testDropdown like this this.testDropdown = [...this.testDropdown,...tempArrayFromApi].

**main error case now** :- when user opens the dropdown and de select the value it automatically makes a double copy of that item and some items in the list goes missing .

**case 2 :-** i also have used .patchValue and .setValue to clear the selection but it does not work .

**Comment by manishjanky** [comment]
You can do that for using an empty array in the setValue/patchValue or null based on the single/multiselect you have.
Or just simply use `patchValue([])` and that will do it.

For the copy one can you please create a demo replicating the issue. I will be able to help better.

**Comment by manishjanky** [comment]
Closing this as there is another issue on the same lines #177
