### ISSUE TITLE
Add option for pushing specific property of selected object to formcontrol and separate property for display

### ISSUE THREAD

**Issue by venki1997** [manishjanky/ngx-select-dropdown#193]
{a:'hi,b:'hello'}
here i want to display property 'a' and push property 'b' to formcontrol

**Comment by manishjanky** [comment]
Its handled in a generic way. You use the whole object as value and pass the `displayKey` in the config for the property that you want to be displayed as option and the formControl can have the whole object as value, and then when you need to use the value just use it like `val.b`.
Hope this helps :)

**Comment by venki1997** [comment]
Hi sirThanks for your reply... The thing is I have used this select npm in dynamic form field.. so i can't access the field directly in addition it will validate in server and throw error when we pass object instead string.. since i used this npm in large scale project i badly need your help... As you see in attachment.... I have obj like this {key:'asset', value :'thing'}In column name i want to show key.. when we select asset i want value property in formcontrol.I want output object for that form like this{Key:'thing', criteria:'is', value:'a', conditions :'not'}Please help me with thisRegardsVenkatesh mOn 25-Jul-2020 9:14 AM, Manish Kumar <notifications@github.com> wrote:
Its handled in a generic way. You use the whole object as value and pass the displayKey in the config for the property that you want to be displayed as option and the formControl can have the whole object as value, and then when you need to use the value just use it like val.b.
Hope this helps :)

**Comment by manishjanky** [comment]
@venki1997 as I said earlier you can use `displayKey` in config to display `key` property and for value when you get it from the control it will be an object ex: `value = {key:'asset', value :'thing'}` now you can access the value using `value.value`

You won't be able to achieve what you are trying completely with the component you will get the value and the use it to get what you need.
