### ISSUE TITLE
Unit tests for the component

### ISSUE THREAD

**Issue by a30001735** [manishjanky/ngx-select-dropdown#195]
Hi,

Any sample code on how to add a unit test for this component. Cannot seem to get the click event to trigger change with spy to work on unit tests. I am using reactive forms.

Thx

**Comment by manishjanky** [comment]
try to trigger a click on the element with the class `ngx-dropdown-button` this will open the dropdown and if clicked again close it.

Also not if using the reactive forms you can use `patchValue` to set the value and then `getValue` to see if the value really changed.

Hope that helps :)
