### ISSUE TITLE
On using overflow:auto/scroll on table, ngx-select-dropdown menu is getting cut off

### ISSUE THREAD

**Issue by jayasingh6** [manishjanky/ngx-select-dropdown#199]

**Comment by manishjanky** [comment]
@jayasingh6 can you create a stackblitz demo for this.
But I thin you can make this dropdown as absolute position and set oveflow to visible. But will be able to help better if I see the issue happening as this seems to be CSS issue and not related to the component.

**Comment by manishjanky** [comment]
Closing this for now. Feel free to comment if you don't come right with this..
