### ISSUE TITLE
Search - Case Sensitive

### ISSUE THREAD

**Issue by Ashajoney** [manishjanky/ngx-select-dropdown#20]
When searching a name in dropdown, it will be good if i could search irrespective of the case. But now it is designed as case sensitive, so only if I give in correct case it is been listed properly.

**Comment by lruiz-invidgroup** [comment]
Is this fix not released yet?

**Comment by PRANABDUTTA** [comment]
It looks really awesome. Please fix the issue of case insensitivity search

**Comment by manishjanky** [comment]
Guys sorry for the delay. Was not keeping well from past few days.
this has been fixed please update to version `v0.4.2`
