### ISSUE TITLE
Clearing values is not working for single selection mode.

### ISSUE THREAD

**Issue by bharath3719** [manishjanky/ngx-select-dropdown#205]
On click of 'X' mark , the items is not getting removed for     [multiple]="false"  , But for    [multiple]="true"  it is. 
Version : 1.4.4
This is my below code :
```
<div class="row">
  <div class="col-sm-12">
    <ngx-select-dropdown #auto
    (change)="selectEvent($event)" 
    [multiple]="false" 
    [config]="dropdownSettings"
    [options]="dropdownList"
    [(ngModel)]="selectedOptions"
    >
    </ngx-select-dropdown>
  </div>
  <span   class="invalid-autocomplete col-sm-12">
    <span *ngIf="!isValid"  class="">{{ errorMsg }}</span>
  </span>
</div>
```

**Comment by sethupsanil** [comment]
I'm also facing this issue

**Comment by HadyAllam** [comment]
I faced the same issue today on **ngx-select-dropdown** v**1.3.1**, I removed **node_modules** and run **npm install** everything works fine after that

**Comment by adisco4420** [comment]
am also having this issue does anyone have a solution to this

**Comment by GobindaSaha** [comment]
same issue

**Comment by GobindaSaha** [comment]
I was facing same issue in Angular 10. But finally I installed ngx-pagination 1.4.0 Everything is working fine now.

**Comment by manishjanky** [comment]
Let me have a look.

**Comment by swetapatil1** [comment]
I am also facing the same issue. Any solution?

**Comment by TalibCode** [comment]
Facing the same issue, is it fixed or not?

**Comment by manishjanky** [comment]
Please try with the latest version.

**Comment by Un1xMida** [comment]
@manishjanky the latest version giving console error like 
ngx-select-dropdown Uncaught TypeError: Object(...) is not a function
