### ISSUE TITLE
Duplicated items when patch the select

### ISSUE THREAD

**Issue by yoedusvany** [manishjanky/ngx-select-dropdown#206]
Hello I'm using this dependencies
`
"dependencies": {
    "@angular/animations": "^9.1.12",
    "@angular/cdk": "^9.2.4",
    "@angular/common": "~9.1.7",
    "@angular/compiler": "~9.1.7",
    "@angular/core": "~9.1.7",
    "@angular/forms": "~9.1.7",
    "@angular/platform-browser": "~9.1.7",
    "@angular/platform-browser-dynamic": "~9.1.7",
    "@angular/platform-server": "~9.1.7",
    "@angular/router": "~9.1.7",
....
   "ngx-select-dropdown": "^1.4.3",`

I pass the options behind an Input var:
@Input() options: [];
and in this component I have a form group
this.registerForm = this.fb.group
that i add a field when a condition occurs

` this.registerForm.addControl(
                'artists',
                this.fb.control(null, Validators.required)
            );`

From another component I use [patchValue to set the values to select

`this.basicRegister.registerForm.patchValue({
                    options: this.options
});
console.log(this.basicRegister.registerForm.controls.options.value); // Show me the correct values
`

but when i see the option into the select (on form) it show me duplicated option sometimes  (one selected and the same unselected)

**Comment by manishjanky** [comment]
Thats expected because you are passing a different object the option property. What you will have to do is make sur the new options you are trying to add does not have any of the existing options.
The filtering of options is left for the user, the component does not caters for that, it displays what it gets.

Hope that helps ;)
