### ISSUE TITLE
Search Issue.

### ISSUE THREAD

**Issue by hayat12** [manishjanky/ngx-select-dropdown#209]
the [search](https://www.npmjs.com/package/ngx-select-dropdown) has an issue, when I want to search an item if I put more than one (1) space then the result shows searching. suppose to trim it. you current implantation if a hit more than one space you add a dot (.), there raise two cases

1. the dot is removable I can remove and can add more space then shows "search ..."
2. adding a dot(.) at the end of the search text is something not cool way none technical people will think oh I did a typo.

An example is added below. event the FMX already exists in the API response. and response already completed but still shows searching.

Suggestion.
better no need to add a dot (.)
if more thing one space don't let the user enter or else trim the keyword.

additional. it would be much better to add clear (x) somewhere next to the arrow (up|down)  

![image](https://user-images.githubusercontent.com/28498116/97042747-140abd00-15a4-11eb-855f-d909d8596272.png)

**Comment by manishjanky** [comment]
I dont know if i completely understand your problem. But from what i can understand, here are my comments:-

1. I dont know which done are you talking about. Also there is that "Search ..." is not part of the component, its users own addition i believe.
2. The addition of (.) is may be your browsers feature and not the component again. The component performs a search on what is typed in the searchbox and nothing else. If you add 2 spaces the components does not adds any (.) dots.

Will see and add a clear(X) for better usability. 
I hope this helps :)
