### ISSUE TITLE
Disable items  from the dropdownlist- this option is not available 

### ISSUE THREAD

**Issue by nuraw** [manishjanky/ngx-select-dropdown#210]

**Comment by manishjanky** [comment]
Yes its not available as you can remove the items you want to disable from the options array and they wont show in the dropdown which i feel is a better option then disabling them and still showing tot he user.
So just remove the items from the options list and they wont show in the  dropdown. I hope that helps.

Let me see if it not too much, i will try and implement it.

**Comment by manishjanky** [comment]
I have added a class 'disabled' to the available option list. based on the item having a disabled property or not. The definition of the class must be written on your side. Will publish soon.
