### ISSUE TITLE
Custom Search function

### ISSUE THREAD

**Issue by debabratapatra** [manishjanky/ngx-select-dropdown#212]
Hi Manish,

It's a great library. Thanks for your effort. I just want to have a custom Search function so that I see results in an order. I tried customComparator, but it is not getting called. Please let me know if there is any other way?

Thanks

**Comment by manishjanky** [comment]
Can you show me the function you used for customComparator?

**Comment by debabratapatra** [comment]
I fixed it using searchChange event. Thanks.
