### ISSUE TITLE
ngx-select-dropdown build issue

### ISSUE THREAD

**Issue by NaseemAhamed** [manishjanky/ngx-select-dropdown#218]
ngx-select-dropdown build issue

#### Bug description
Argument mismatch issue with relevant to SelectDropDownComponent file while doing a prod build. It works fine in 0.7.2 version, but this version does not have the essential down arrow icon on the right. Can someone please fix this issue in the latest version 1.5.0? 

#### Expected result
It needs to compile successfully

#### Actual result

node_modules/ngx-select-dropdown/dist/components/ngx-select-dropdown-component/ngx-select-dropdown.component.d.ts.SelectDropDownComponent.htm
l(3,59): Expected 0 arguments, but got 1.

#### Steps to reproduce

1. Please run the prod build 'ng serve --prod' or do a build with 'ng build --prod'

#### Context  
Trying to populate <select> values from the backend with a searchable option.  -----

#### Your Environment:  
Prod build in local machine.  -----

* Version used: 1.5.0 -----
* Browser Name and version: Chrome - 88.0.4324.150 [Latest build]  -----
* Operating System and version: Windows - 10

**Comment by manishjanky** [comment]
@NaseemAhamed  the build works fine on my side. What is you version of angular?

**Comment by NaseemAhamed** [comment]
> @NaseemAhamed the build works fine on my side. What is you version of angular?

Please find the version below. It is 11. @manishjanky 

Angular CLI: 11.0.4
Node: 12.19.0
OS: win32 x64

Can we please make it work there if it is an easy fix? :( I did not face any issues with it in my local build. Now that we are going to deploy it in staging, we need to have the prod build.

**Comment by manishjanky** [comment]
Please update to the lates version `v2.0.0`
