### ISSUE TITLE
Custom Classes on the options field

### ISSUE THREAD

**Issue by mayanksunder1** [manishjanky/ngx-select-dropdown#219]
please add a feature to add custom classes on options of dropdown based on condition

**Comment by mayanksunder1** [comment]
Any  Update ?????

**Comment by manishjanky** [comment]
Give me some time, will look into this..

**Comment by anilkaushik1211** [comment]
Hi @manishjanky,

I require the feature (support of custom CSS/Style) for one of my projects.
Do we have any updates for this?

**Comment by manishjanky** [comment]
@mayanksunder1 / @anilkaushik1211 not exactly what it should be but you can now add you css styling on to the already assigned classes. To override use `!important` and for the properties that do not already having any value just assign values usually.
update to vision greater than `v3.0.0`
