### ISSUE TITLE
how to reset the drop down after submitting?

### ISSUE THREAD

**Issue by sukumardhoni** [manishjanky/ngx-select-dropdown#22]
i am selecting some values with ngx-select-dropdown , so after selecting i am resetting my form but i am an unable to reset ngx-select-dropdown with default label (select).

**Comment by manishjanky** [comment]
You have a model property binded to the `value` of the dropdown. `[(value)]="modelProperty"` In order to reset the value when resetting the form. Just set that to an empty array `modelProperty=[]`. 
Yes there should be a way to just set it to null or undefined Just noticed that it works but partially. Will be adding that in a day or two. Thanks for bringing this up.
Hope this helps :)

**Comment by sukumardhoni** [comment]
thanks for ur reply,
i had already tried this in a way setting the `modelProperty = [].` but this not worked for me?
[(value)]="modelProperty" is html element , This is how i tried.

<ngx-select-dropdown [config]="config" [options]="DataArr" [(value)]="modelProperty " [multiple]="false" (change)="selectData(modelProperty )">
 </ngx-select-dropdown>

.ts
--
modelProperty 

.subscribe(res => {
this.form.reset()
this.modelProperty = [];
})


Thanks,

**Comment by manishjanky** [comment]
Ok let me have a look will get back to you soon.

**Comment by manishjanky** [comment]
@sukumardhoni i tried this. Setting the modelProperty to any empty array  `modelProperty=[]` works fine. There might be something else can you share a piece of code to replicate the issue.

**Comment by sukumardhoni** [comment]
@manishjanky After form submission the modelProperty is assigned with an empty array `modelProperty=[]` , i had also debugged this value , it is emptying that property as expected but the thing is the value which i had selected in the dropdown is still presenting there even after i assigning to `modelProperty=[]`? 

{{modelProperty | json}} //initially when i have selected , this feild has some values in it.
<ngx-select-dropdown [config]="config" [options]="DataArr" [(value)]="modelProperty " [multiple]="false" (change)="selectData(modelProperty )">

<form  [formGroup]="form" (ngSubmit)="formSubmit()">
//form fields like inputs
</form>

export class  Demo implements OnInit {
modelProperty 

formSubmit(){
this.authService.createUser()
.subscribe(res => {
this.form.reset() //resetting my form sucessfully 
this.modelProperty = []; // {{modelProperty | json}} // clearly this array become empty here also in html(refer above) .
})
}

}

//even though the selected drop down still existing with the value which i was previously selected.
I need to show the dropdown like how it is initially (select place holder). but this not happening?
I also tried with emptying the   DataArr property as well.

**Comment by sukumardhoni** [comment]
Angular 4

**Comment by manishjanky** [comment]
The ngx-select-dropdown version i m asking.

**Comment by sukumardhoni** [comment]
"ngx-select-dropdown": "^0.3.2"

**Comment by manishjanky** [comment]
Please update to the latest version this has been already fixed. Also there no breaking changes but new fetures you would like. Latest version `v0.5.1`

**Comment by DakshKhetarpal** [comment]
not working...

**Comment by satyendersaini56** [comment]
I have also the same issue. 

<ngx-select-dropdown (change)="ddlBrandChange(od.vendorCode,'price',od,selectedBrand)"
                [(ngModel)]="selectedBrand" 
                [config]="{displayKey:'brandName',search:true,height: '300px'}"
                [options]="myArray">
              </ngx-select-dropdown>

In .ts file i did  selectedBrand=null/undefined/{}
nothing working

**Comment by AlkenArt** [comment]
Any update on the latest question. I'm facing the same issue.
the ngModel field is assigned with undefined/null/{} nothing is working on v1.0.1
