### ISSUE TITLE
Module not found: Error: Can't resolve 'D:\Angular\node_modules\ngx-select-dropdown\dist\assets\style.css'

### ISSUE THREAD

**Issue by 8013853290** [manishjanky/ngx-select-dropdown#224]
please help me.

Module not found: Error: Can't resolve 'D:\Angular\node_modules\ngx-select-dropdown\dist\assets\style.css'

**Comment by manishjanky** [comment]
Which version are you using. The style.css is no longer required from v1.4.0 onwards. Please read the docs again.

**Comment by jackz7** [comment]
you have to remove the style entry from angular.json if included previously
