### ISSUE TITLE
Search box is not woking

### ISSUE THREAD

**Issue by sumanthurs** [manishjanky/ngx-select-dropdown#23]
it is showing the search box in dropdown but if we type anything in search box it remains same.

html:
					<ngx-select-dropdown 
						[config]="config" 
						[options]="dropdownOptions" 
						[(value)]="dataModel"
						[multiple]="true">
					</ngx-select-dropdown>

ts:
 config = {
    displayKey:"name", //if objects array passed which key to be displayed defaults to description,
    search:true 
    }

**Comment by thari119** [comment]
Im facing the same issue. any fix for this?

**Comment by VinayKrMittal** [comment]
@manishjanky 

Hi, 
I am using "ngx-select-dropdown" and dropdown options as array of objects as:

"data": [{
		"id": 1060,
		"emailId": "vinay@wavene.com",
		"phoneNumber": "3333333334",
		"userName": "vinayK",
		"firstName": "Vinay",
		"lastName": "Mittal",
		"employeeId": "E987\t",
		"type": 0,
		"address": "mmkmkmk",
		"centreId": 12,
		"createTime": "2018-07-18T10:40:59.000Z",
		"state": 0,
		"shift": 0
	}, {
		"id": 1061,
		"emailId": "xyz@gmail.com",
		"phoneNumber": "1234567890",
		"userName": "anand1",
		"firstName": "Anand",
		"lastName": "Kumar",
		"employeeId": "anand123",
		"type": 0,
		"address": "Gurgaon",
		"centreId": 12,
		"createTime": "2018-07-18T11:18:38.000Z",
		"state": 0,
		"shift": 0
	}, {
		"id": 1062,
		"emailId": "sds@wds.com",
		"phoneNumber": "3456789545",
		"userName": "anand123",
		"firstName": "Anand",
		"lastName": "Kumar",
		"employeeId": "anand1234",
		"type": 0,
		"address": "fdfsds",
		"centreId": 12,
		"createTime": "2018-07-19T06:56:36.000Z",
		"state": 1,
		"shift": 0
	}, {
		"id": 1063,
		"emailId": "ran@jeet.co",
		"phoneNumber": "7889786778",
		"userName": "Ranjeet",
		"firstName": "Ranjeet",
		"lastName": "Chand",
		"employeeId": "E006",
		"type": 0,
		"address": "Gurgaon27",
		"centreId": 12,
		"createTime": "2018-07-26T06:51:27.000Z",
		"state": 1,
		"shift": 2
	}]

i want to display userName as display key in dropdown and get id as value.
i have set config object as

  config = {
    displayKey: "userName",
    placeholder: "Select Username", 
    search: true,
    ismultiple: false  //enables the search plugin to search in the list
  }

but it shows me something like: [object,object] .

Please correct me if anything goes wrong...

can you please help. 

version:  "^0.7.0"

**Comment by vugardadalov** [comment]
`{
      displayKey: "name",
      search: search,
      height: '50vh',
      placeholder: 'Select',
      moreText: 'More',
      noResultsFound: 'Not found',
      searchPlaceholder: 'Search',
      searchOnKey: 'name',
      limitTo: 200
    }`

`displayKey` is default 'description'
