### ISSUE TITLE
dropdown reset is not working in 2.1.0

### ISSUE THREAD

**Issue by sedhurabe** [manishjanky/ngx-select-dropdown#236]
#### Bug description

In ngx-select-dropdown 2.1.0 I not able to reset the dropdown value. `[_value]="dataModel"`. if I send the the `dataModel` empty array also its not working. @manishjanky

**Comment by hanisani** [comment]
You have to set the [(ngModel)]="selectedItem"
Here selectedItem is one of the dropdown options.
Hope it helps.
Thanks.

**Comment by manishjanky** [comment]
@sedhurabe  as suggested by @hanisani  please use [(ngModle)] `_value` is not a Input property.
