### ISSUE TITLE
Within table, changing value in one dropdown changes for all

### ISSUE THREAD

**Issue by hanisani** [manishjanky/ngx-select-dropdown#239]
Let say, you are using **ngx-select-dropdown** within a table. 
And table rows are dynamically generated using ***ngFor**. 
Then if we change the value of **ngx-select-dropdown** in a particular row, 
noticed that all the rows dropdown values are changed as shown below.
Any idea how to fix in Angular?

![image](https://user-images.githubusercontent.com/29116663/121680248-39a3f280-cab1-11eb-8993-d6d05ad5495d.png)

**Comment by manishjanky** [comment]
@hanisani in that case you have to make sure that the bindings are set accordingly. What I can say for now is that all you dropdown are binded to the same property and hence when the value of one changes the same reflects on the others too.
