### ISSUE TITLE
Search not working, input not accepting any characters

### ISSUE THREAD

**Issue by VlnRbn** [manishjanky/ngx-select-dropdown#24]
Hi @manishjanky 
Thanks for plugin, Currently using it in a project
I have enabled `search = true` in config, search box displays in UI, but not accepting any characters.

Any help or suggestion is appreciated.

**Comment by rakesh2293** [comment]
Hi team
I  also encounter this issue.  please support

**Comment by manishjanky** [comment]
Which version are you guys using?

**Comment by rakesh2293** [comment]
@manishjanky 
 "ngx-select-dropdown": "^0.5.0",

**Comment by rakesh2293** [comment]
ok Manish  
Thank you for your response

**Comment by manishjanky** [comment]
Please update to `v0.5.1` this has been fixed.
