### ISSUE TITLE
Previously selected options go to the bottom of the dropdown

### ISSUE THREAD

**Issue by mhasibi** [manishjanky/ngx-select-dropdown#246]
#### Bug description

When you select an option off the dropdown , it disappears from the dropdown , and when you click on another option , you will not find the previously chosen option back in its place , but at the end of the list (bottom of the dropdown).
This makes the dropdown list kind of shuffle all the time and look inconsistent.
#### Expected result

The option should go back to its place in list, where it was before being selected.
#### Actual result

The previously selected option is found at the end of the list.
#### Steps to reproduce

1. Select an option from the dropdown menu ; say, option A. Option A is removed from the option list and displayed on top of the list.
2. Select another option; say, option B. Option B is removed from the option list and displayed on top of the list.
3. Option A is no longer where it used to be in the list. It is found at the bottom of the list - end of dropdown options - .
#### Context

Trying to create a dropdown using this package

#### Your Environment

* Version used: 
* Browser Name and version: Google Chrome, Version 95.0.4638.54
* Operating System and version: Windows 10
* Link to your project:

**Comment by manishjanky** [comment]
@mhasibi  you can you the `customComparator` which is part of the `config` property and is a sorting function will display the items sorted as per the function.
