### ISSUE TITLE
Request for adding limit for loading data in drop down

### ISSUE THREAD

**Issue by zahid1132** [manishjanky/ngx-select-dropdown#26]
I have 15000 data to load in drop own, So want to limit data size first, when I search then related data load to drop down like as Type Head.

**Comment by manishjanky** [comment]
@zahid1132 give me some time will implement.

**Comment by manishjanky** [comment]
please update to `v0.7.0`

**Comment by sairamchinna** [comment]
when am loading 5000 records for binding it is taking too time Browser stoped, and at least the above case also not working in latest version of **v0.7.2**. Do i need to change any config for this after getting response..? Please replay ASAP. TIA
