### ISSUE TITLE
If i add close event on all ngx-select-dropdown in one form. Then, close event calls for all the ngx-select-dropdown if i just close any of them. why ?

### ISSUE THREAD

**Issue by Ahtesham0786** [manishjanky/ngx-select-dropdown#263]
#### Steps to reproduce

1.
2.
3.
#### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:
* Link to your project:

**Comment by manishjanky** [comment]
Will you be able to share a demo of this on stackblitz. This is very little information to replicate this.
