### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by umarahmaddh** [manishjanky/ngx-select-dropdown#266]
#### Is your feature request related to a problem? Please describe.
  I am using It on my web when I open it on Android it works well but on iPhone Not Working Well in any browser.
  Not select the option.
#### Describe the solution you'd like
Can You guide Me to solve this

**Comment by manishjanky** [comment]
Please have a look at this closed issue https://github.com/manishjanky/ngx-select-dropdown/issues/264
Update to the latest version.
