### ISSUE TITLE
On Search it gives error on second time search.

### ISSUE THREAD

**Issue by umarahmaddh** [manishjanky/ngx-select-dropdown#267]
#### Bug description
step 1: Search and select item.
step 2 : again open the drop down and type in search input, it will not work and gives error in console.

im adding [(ngModel)]="selectedCountry"
if i remove this it is working fine,
With [(ngModel)] it gives error.
I have to use  [(ngModel)]  because i have to patch value from api.
#### Expected result
it should search again.
#### Actual result
not searching second time.

this is the error in the console.:
core.mjs:7635 ERROR TypeError: item.toLowerCase is not a function
    at ngx-select-dropdown.mjs:51:48
    at Array.filter (<anonymous>)
    at FilterByPipe.transform (ngx-select-dropdown.mjs:51:26)
    at pureFunction3Internal (core.mjs:22483:65)
    at Module.ɵɵpipeBind3 (core.mjs:22680:9)
    at NgxSelectDropdownComponent_div_3_Template (ngx-select-dropdown.mjs:676:2663)
    at executeTemplate (core.mjs:12084:9)
    at refreshView (core.mjs:11969:13)
    at refreshEmbeddedViews (core.mjs:12997:17)
    at refreshView (core.mjs:11993:9)

* Version used: latest 3.1.3
* Browser Name and version: Chirome Latest
* Operating System and version: windows.
* Link to your project:

**Comment by manishjanky** [comment]
The reason for this might be the difference in the [(ngModel)] value and the options. i.e. the objects may not match the structure. Can you share those details.
Because if you try this on the demo here. it works fine without any errors.
https://manishjanky.github.io/ngx-select-dropdown/

**Comment by umarahmaddh** [comment]
yes, thanks for answering.
 [(ngModel)] value and options were not matching the structure. working now thanks.
