### ISSUE TITLE
Getting some issue from today.

### ISSUE THREAD

**Issue by Abhishekm7376** [manishjanky/ngx-select-dropdown#269]
#### Bug description

Today suddenly I got this error.

ERROR TypeError: Cannot read properties of undefined (reading 'disabled')
    at NgxSelectDropdownComponent_div_5_li_6_Template

Till yesterday it was working fine. I am using this for the last year. Today this alert came. I didn't change anything in the code. Please help me.
#### Steps to reproduce

1.
2.
3.
#### Your Environment

* Version used:
* Browser Name and version:
* Operating System and version:
* Link to your project:

**Comment by manishjanky** [comment]
@Abhishekm7376 its very little information to investigate. Can you please try and create a stackblitz to replicate this.. Also can you double check you bindings..

**Comment by Abhishekm7376** [comment]
Thank you. It got resolved.
