### ISSUE TITLE
space in the start or end while searching should be trimmed.

### ISSUE THREAD

**Issue by dhudhaall** [manishjanky/ngx-select-dropdown#270]
#### Bug description
while searching in dropdown, if space is added in the start it does not search the string. space should be trimmed off from start and end.

![image](https://user-images.githubusercontent.com/38068731/202115043-5f648966-54c2-42bf-9ded-847300dcd522.png)

#### Expected result

if there is space in the start it should search the matching 
#### Steps to reproduce

Try searching with adding space in the start. it will not work

**Comment by manishjanky** [comment]
Please update to the latest version `v3.3.0`
