### ISSUE TITLE
Issue in search tool

### ISSUE THREAD

**Issue by EduardoAndretta** [manishjanky/ngx-select-dropdown#273]
<p align="center">
<img src="https://user-images.githubusercontent.com/82424514/205080942-eb68e9c7-712e-4610-b295-a794345a689e.png">
</p>

When removing the "X", search stop to working and handle this error in console.log at each key pressed.

<p align="center">
<img src="https://user-images.githubusercontent.com/82424514/205080197-2a7d3bdf-842e-4981-bbff-40a11e6dcbcd.png">
</p>

I try to fix this issue with this code (fesm2020/ngx-select-dropdown.mjs).

```
if (item[keyName] !== undefined) 
{
     if (typeof item[keyName] !== 'object' && item[keyName].toString().toLowerCase().indexOf(searchText.toLowerCase()) > -1) 
     { 
     return true;
     } 
}    
return false;
```

**Comment by manishjanky** [comment]
Can you share more details.. Like what does your items array look like? Your config you are using for the dropdown..
If you can replicate it in a stackblitz that will really help me investigate this.
