### ISSUE TITLE
[(_value)] -> selected value is getting duplicated in Dropdown list

### ISSUE THREAD

**Issue by arpudhanaresh** [manishjanky/ngx-select-dropdown#276]
Selected Value is getting duplicated in List
#### Bug description
The selected value is getting duplicated in Dropdown list
For Example -> while passing the value to formgroup ,  the selected value is not getting selected in already existing list,
instead it adding  a new List with duplicate Name

#### Expected result

Expected value "Arpudha"  should be selected in already available list
#### Actual result

<img width="281" alt="image" src="https://user-images.githubusercontent.com/59797552/209085409-93ed82cd-6c55-4e87-ac40-10e637f2eb23.png">

#### Steps to reproduce

1. assign a list of 3-4 values to the dropdown, one of the value should be "Arpudha"
2. now pass the value "Arpudha" to the selecteddropdown value [(_value)} = "selectedValue"
3.This makes duplicate value in the list

**Comment by manishjanky** [comment]
Hey @arpudhanaresh you are using it wrong. Its not to be used like `[(_value)} = "selectedValue"` instead you should use 
`[(ngModel)} = "selectedValue"`
