### ISSUE TITLE
Clicking the scrollbar of dropdown content closes the dropdown

### ISSUE THREAD

**Issue by RandomPrecision1** [manishjanky/ngx-select-dropdown#278]
#### Bug description
If the dropdown has sufficiently many options to have a scrollbar, users can use the mousewheel to scroll - but clicking or dragging the scrollbar itself causes the dropdown to close.

#### Steps to reproduce
This can be created by either

A.) setting up an instance of the dropdown with enough options to scroll, or 
B.) opening the demo at https://manishjanky.github.io/ngx-select-dropdown/ and using developer tools to change the max-height of .ngx-dropdown-container to 150px

#### Example
![Animation](https://user-images.githubusercontent.com/18370355/214950371-574b2902-37ab-49c6-add1-92910690c21f.gif)

**Comment by manishjanky** [comment]
What browser are you facing this issue in?

**Comment by RandomPrecision1** [comment]
@manishjanky sorry, didn't see your response until just now! I've seen it with:

- Chrome 111.0.5563.65 64-bit
- Edge 111.0.1661.44 64-bit

**Comment by manishjanky** [comment]
@RandomPrecision1 can you see if the latest version fixes this on your end. 
Turned out to be a tricky one. I have tried to fix it.. let me know if it is not

**Comment by RandomPrecision1** [comment]
@manishjanky it looks like version 3.3.1 resolves it - thanks for looking into this!
