### ISSUE TITLE
Can't get the scroll bar to appear

### ISSUE THREAD

**Issue by pak12** [manishjanky/ngx-select-dropdown#28]
activityConfig
   = {
    height: 'auto', //height of the list so that if there are more no of items it can show a scroll defaults to auto. With auto height scroll will never appear
  }

I have set the height to, for example, 5, but the scroll bar didn't show even  when I have 50 items.

**Comment by manishjanky** [comment]
You have to specify the unit as well. It should be '5px'

**Comment by manishjanky** [comment]
Did you got this sorted out.

**Comment by pak12** [comment]
Yes it works!
Thanks

在 2018年7月13日週五 21:30，Manish Kumar <notifications@github.com> 寫道：
