### ISSUE TITLE
Can't type in a filter value on iPhone OS 16.3.1 in any browser app (Safari, Firefox, Chrome)

### ISSUE THREAD

**Issue by softmillennium** [manishjanky/ngx-select-dropdown#283]
Trying to do a filtered search for select items:
1. Click on the drop down
2.  text box appears, but when tapping on it to type anything in, it closes.

#### Expected result
dropdown control should allow the user to type in a search filter value

#### Actual result
 tapping on the open dropdown text input , closes the dropdown making it impossible to type anything in.
#### Steps to reproduce
1. Click on the drop down
2.  textbox appears, but when tapping on it to type anything in, it closes right away.

#### Context
The control works in Chrome and Firefox browsers on MacOS

#### Your Environment
The control doesn't work on any browser apps on iPhone OS 16.3.1

* Version used: 3.3.0
* Browser Name and version: Safari on MacOS, any browser on Iphone 12 Pro OS 16.3.1
* Operating System and version: 
* Link to your project:

**Comment by manishjanky** [comment]
Please update to latest version.
