### ISSUE TITLE
Click on Search input closes the dropdown in Safari Mac and iOS

### ISSUE THREAD

**Issue by AAmeriyan** [manishjanky/ngx-select-dropdown#284]
its ok in Chrome and Mozilla firefox but in Safari on clicking or Touching search input closes the drop down but if we select an item we can select Search input

**Comment by HammadManzoor** [comment]
Has this always been an issue and are there any updates on a fix for it?

**Comment by ahmedkhairydev** [comment]
the safari browser feels the input focus event as a click outside of the `ngx-dropdown-list-container`. 
can you fix it? @manishjanky

**Comment by manishjanky** [comment]
Please upgrade to latest version.
