### ISSUE TITLE
NgxDropdownConfig are not optional in typescript

### ISSUE THREAD

**Issue by richard-muvirimi** [manishjanky/ngx-select-dropdown#287]
#### Bug description
First of all, thank you for a great package. However, there is one issue when using the package with typescript. the [READ.ME](read.me) page lists some of NgxDropdownConfig options as being optional but since the interface (below) definition defines them as non-null you have to provide them on every `ngx-select-dropdown` config.
```
export interface NgxDropdownConfig {
    displayFn?: any;
    displayKey: string;
    search: boolean;
    height: string;
    placeholder: string;
    customComparator: (a: any, b: any) => number;
    limitTo: number;
    moreText: string;
    noResultsFound: string;
    searchPlaceholder: string;
    searchOnKey: string;
    clearOnSelection: boolean;
    inputDirection: string;
    selectAllLabel?: string;
    enableSelectAll?: boolean;
}
```

#### Expected result
It would make more sense to provide these options to the root option when we import the module using `forRoot` and only override a few options depending on where the `ngx-select-dropdown` is shown instead of having duplicated code throughout the application. To address the above issue, marking the interface options as optional as indicated in the documentation would be a good first start.

#### Actual result
Qouted below is the error from Webstorm IDE on just commenting out `displayKey` which is the same for every other option documented as optional in the [READ.ME](read.me)

Property  displayKey  is missing in type
```
{     
  clearOnSelection: false;    
  customComparator(a: any, b: any): number;   
  height: string; 
  inputDirection: string;  
  limitTo: number;   
  moreText: string;   
  noResultsFound: string; 
  placeholder: string;  
  search: true;  
  searchOnKey: string;    
  searchPlaceholder: string; 
}
```
but required in type  NgxDropdownConfig 

#### Steps to reproduce

1. Create an `ngx-select-dropdown` element.
2. Add `[config]` attribute with a few options.
3. Typescript will highlight the other options as being required.
#### Context
Faced with having to define 5 - 10 config options per page depending on the context of the dropdown, a normal select might appear more appealing.

#### Your Environment

* Version used: 3.3.1
* Browser Name and version: Not Relevant.
* Operating System and version: Windows 11.
* Link to your project: Not Applicable.

**Comment by manishjanky** [comment]
What version of typescript do you have?

**Comment by richard-muvirimi** [comment]
Typescript version: ~4.8.4

**Comment by manishjanky** [comment]
Please upgrade to the latest version
