### ISSUE TITLE
Single select dropdown search functionality

### ISSUE THREAD

**Issue by rajkanase** [manishjanky/ngx-select-dropdown#33]
If we search and select a option in **single select** drop down. Another options gets invisible and we need to reload the page to see them again. same functionality working fine for multiple select drop down.

**Comment by manishjanky** [comment]
Let me have a look will update you soon.

**Comment by manishjanky** [comment]
will publish it this weekend by then you can install it using the below command
`npm install manishjanky/ngx-select-dropdown`
