### ISSUE TITLE
How can i deselect item?

### ISSUE THREAD

**Issue by sehven-zavzen** [manishjanky/ngx-select-dropdown#35]
Hello

Thanks for this amazing component. I'm trying to unselect item after an operation. I mean dropdown will return to its default ("Select this") with data. I need to do this after button click. I tried many ways but i guess i have problem about binding. I destroyed dropdown data.. How can i achieve this?

Thanks

**Comment by manishjanky** [comment]
To deselect an item you can set the value to an empty array [] that will do.

**Comment by sehven-zavzen** [comment]
But then it removes selected data from dropdown data, doesn't it?

**Comment by manishjanky** [comment]
Yes it will. For that you can reset the options array that is reinitialize it

**Comment by sehven-zavzen** [comment]
Ok, ty :)
