### ISSUE TITLE
How I can reset selected values?

### ISSUE THREAD

**Issue by DGanapathi** [manishjanky/ngx-select-dropdown#39]
I'm doing as below and values are getting reset but reset values are not displaying again in the drop-down available list. 
<ngx-select-dropdown (change)="changeValue($event)"  [multiple]="true" [(value)]="SelectedValues" [config]="config" [options]="myOptions"></ngx-select-dropdown>

onClearButtonClick()
{
this.SelectedValues=[];
}

**Comment by manishjanky** [comment]
this should do it. 
`onClearButtonClick()
{
this.SelectedValues=[];
this.myOptions = [...this.myOptions];
}`

Please let me know if you still face issues.

**Comment by DGanapathi** [comment]
Its working, Thank you Manish :)
