### ISSUE TITLE
ngx-select-dropdown does not work with angular 6

### ISSUE THREAD

**Issue by ajit-soman** [manishjanky/ngx-select-dropdown#40]
I am getting this error:

```
ERROR in node_modules/ngx-select-dropdown/dist/components/ngx-select-dropdown-component/ngx-select-dropdown.component.d.ts(2,10): error TS2305: Module '"/home/ajit-soman/git/test/node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/rxjs/Rx.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat'.
node_modules/rxjs/Subject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subject'.
```
After following installation steps , I run the project with ng serve and found these error in terminal

My project has angular version `6.1.0` and rxjs version `6.0.0`

Is there any way to fix this issue without downgrading rxjs or angular version

**Comment by manishjanky** [comment]
@ajit-soman yes it wont because it's built over `rxjsv5.3.1` and `rxjsv6.0.0` has breaking changes. it wont work.
Let me see what i can do.

**Comment by manishjanky** [comment]
Yes it is. Have removed rxjs dependency. Still need to test once properly if will have issues with angular 6 or not. Will publish soon and update you on the same.

**Comment by manishjanky** [comment]
Hi
Can you please give it a try now. Update to v0.7.2 and try. Please let me know if you still face any issues.

**Comment by manishjanky** [comment]
Closing this as this has been fixed. PFB the stackblitz demo that where `ngx-select-dropdown` works with angular 6.
[Stackblitz Demo With Angular 6](https://stackblitz.com/edit/angular-crjqyw)
