### ISSUE TITLE
Errors out when using required field validation

### ISSUE THREAD

**Issue by darshanaw** [manishjanky/ngx-select-dropdown#41]
When required fields validation are done on the control, it errors out. The attachments will give more insight.

![image](https://user-images.githubusercontent.com/40012508/43694919-09612fbe-9979-11e8-942f-cf68e42781c9.png)

![image](https://user-images.githubusercontent.com/40012508/43694941-26e214fe-9979-11e8-9c71-1c1a4a5af401.png)

**Comment by manishjanky** [comment]
Its not a form element an html input element so it wont support required attribute. But angular forms support will be coming soon..

**Comment by cbjpdev** [comment]
Any update regarding this? is there any workaround to do validations?

**Comment by manishjanky** [comment]
@darshanaw @cbjpdev. Angular forms supports has been added. Please give it t try. Update to `v1.0.0`. Let me know if you face any issues.
Hence closing this.

**Comment by akilaKathirc** [comment]
validations are triggered automatically on component load
