### ISSUE TITLE
Not appear "X" on the selected values

### ISSUE THREAD

**Issue by alvarogonjim** [manishjanky/ngx-select-dropdown#43]
Hello,
I installed the library on my project, it works fine but it won't appear the "X" icon to deselect. You can see in the next pictures:

![expected](https://user-images.githubusercontent.com/25668523/43887013-c99f5062-9bbd-11e8-820c-ef581aafc638.png)
_Expected results_

![error](https://user-images.githubusercontent.com/25668523/43886996-b48d53cc-9bbd-11e8-9095-e14adda7e6ff.png)
_My results_

Note: I imported the styles from  _"../node_modules/ngx-select-dropdown/dist/assets/style.css"_
Thanks so much.

**Comment by manishjanky** [comment]
Did you include the style.css file.in your build in angular-cli.json?. That must be the reason for this.

**Comment by manishjanky** [comment]
Not sure can you please create a demo for me to replicate this issue.

**Comment by alvarogonjim** [comment]
We use webpack, we we have a different structure and we use scss, for these reasons the integration is different. Don't worry we could fixed the problem. 
Thanks so much, I'll close the issue. :+1:
