### ISSUE TITLE
add support to ssr

### ISSUE THREAD

**Issue by alexthelion** [manishjanky/ngx-select-dropdown#44]
The component is not working with server side rendering (universal + angular 6).
I'm getting to following error:

> TypeError: ctor is not a constructor
>     at _createClass (webpack:///./node_modules/@angular/core/fesm5/core.js?:8716:20)
>     at _createProviderInstance (webpack:///./node_modules/@angular/core/fesm5/core.js?:8690:26)
>     at initNgModule (webpack:///./node_modules/@angular/core/fesm5/core.js?:8623:32)
>     at new NgModuleRef_ (webpack:///./node_modules/@angular/core/fesm5/core.js?:9349:9)
>     at Object.createNgModuleRef (webpack:///./node_modules/@angular/core/fesm5/core.js?:9338:12)
>     at NgModuleFactory_.create (webpack:///./node_modules/@angular/core/fesm5/core.js?:11880:25)
>     at eval (webpack:///./node_modules/@angular/core/fesm5/core.js?:4610:43)
>     at ZoneDelegate.invoke (webpack:///./node_modules/zone.js/dist/zone-node.js?:387:26)
>     at Object.onInvoke (webpack:///./node_modules/@angular/core/fesm5/core.js?:4121:33)
>     at ZoneDelegate.invoke (webpack:///./node_modules/zone.js/dist/zone-node.js?:386:32)

**Comment by AndriusdevLa** [comment]
Hello, I am getting error : 

Unexpected token { at : 

C:\Users\andri\OneDrive\Desktop\Jobify\front-end\careerfy\front-end\node_modules\ngx-select-dropdown\dist\components\ngx-select-dropdown-component\ngx-select-dropdown.component.js:9
import { Component, Input, EventEmitter, Output, HostListener, ViewChildren, ElementRef, ChangeDetectorRef, forwardRef } from "@angular/core";
       

when I run npm run serve:srr 

We cant use your dropdown with SSR, when it will be fixed ?

**Comment by manishjanky** [comment]
Hi @AndriusdevLa @alexthelion can you please try now with the latest version. I have tested on my end, works fine with ssr without any errors.

**Comment by manishjanky** [comment]
The component works with SSR hence closing this issue.
