### ISSUE TITLE
Npm install "manishjanky/ngx-select-dropdown" not working

### ISSUE THREAD

**Issue by hirokimoto** [manishjanky/ngx-select-dropdown#5]
Hello

I am sure **npm install "manishjanky/ngx-select-dropdown" not working** should be working.
You know, all third party libraries could be installed that way.
But this library would not work on that command.
Could you please fix it on your end?

**Comment by manishjanky** [comment]
@hirokimoto i have tried this it works fine for me.  
````
npm install manishjanky/ngx-select-dropdown
````
Try it without quotes.
Also if you get any error  or any logs that might help please share and any information also that might help.

**Comment by hirokimoto** [comment]
Thanks for your quick reply, and please take a look at the differences in folder structures between npm install **ngx-select-dropdown** and **npm install manishjanky/ngx-select-dropdown**.
If you do **npm install manishjanky/ngx-select-dropdown**, you can't find dist folder in ngx-select-dropdown in node_modules.
That brings issues.

**Comment by manishjanky** [comment]
Ok, that should not be the case because thats a valid way of installing a package as per npm docs. Still let me have a look into this and get back.

**Comment by hirokimoto** [comment]
Thanks.

Also, I am going to create a PR to fix a bug, is it okay with you?

**Comment by manishjanky** [comment]
Ya sure as far as it solves a bug a PR is welcome. 
Any ways what is the bug?

**Comment by hirokimoto** [comment]
I have just created PR, can you review it?

**Comment by manishjanky** [comment]
Sure i will :)

Also i did a bit of research into this way of installing the packages. So its actually like 
````
npm install <github-username>/package-name
````
What happens in this case according to my understanding is it takes all the files/folders not specified in `.npmingnore` and install the package. dist folder is one of them but as the dist folder is not present in the github repository so only its not part of the installed folder in our case.

I think that should be fine not inlcuding dist folder in source control. But still will a do a bit of more research on this and see if this way of installing package really needs to be supported as `npm install package-name` just works absolutely fine.

**Comment by manishjanky** [comment]
Closing this as this way of installing is not much needed. Also my bad, referenced it in the wrong  commit.

**Comment by thilankascentic** [comment]
Hi Any update on this issue ?

**Comment by hirokimoto** [comment]
Hello

I think this should be fixed. If you fork this repo, and customize something, and try to install, you can notice that this issue should be fixed.

**Comment by manishjanky** [comment]
@thilankascentic as explained in my earlier comment. I think its not really necessary to add `dist` folder in the repo. 
Also if a use is trying to install it this way. He can install it with the usual way as both needs npm and there are no name conflicts in npm as it does not allow two packages to have same name. So `npm install ngx-select-dropdown` should just work fine. 

Also i have not seen dist folder being part of the repository for other plugins/packages.

Lets see if there really comes a need to support this way installing will do. Till the the usual way is the way to go.

**Comment by hirokimoto** [comment]
@manishjanky This is really needed because the forked library could be installed in that way, username/library name.
I have tried to fork, add some functionalities, and install it, but it never worked, because of this issue.
Thanks.

**Comment by manishjanky** [comment]
@hirokimoto what you can try is -- As you have forked the repo have made some changes and now trying to install it with `npm install your-username/ngx-select-dropdoen` right?

In this case you can edit your `.gitingnore` i.e include dist folder in your source control and commit. and then try installing. Then it should work i think. Give it a try and let me know.
