### ISSUE TITLE
SelectDropdownOption text gets injected in the wrong place in the Multi Select Dropdown

### ISSUE THREAD

**Issue by brimwd** [manishjanky/ngx-select-dropdown#52]
As you can see in this screen capture, after selecting an option in the Multi Select Dropdown, the option text is injected directly into the `.nsdicon-close` span instead of being injected **after** the icon span into the same parent `li`.
<img width="360" alt="screen shot 2018-09-14 at 1 41 27 pm" src="https://user-images.githubusercontent.com/5776635/45574197-09599780-b824-11e8-8eef-5178f83f11ac.png">

As a result of this, the text in the `li` takes on the icon's font-family (a light-weight serif font) instead of inheriting the font-family used in the rest of the application.

**Current workaround:** it's possible to workaround the issue with the following CSS:
```
.ngx-dropdown-list-container ul.selected-items li span {
  font-family:inherit !important;
}
.ngx-dropdown-list-container ul.selected-items li span::before {
  font-family:'icomoon' !important;
}
```

**Expected behavior:** The text should be injected into its own `span` with a class so that the text can be styled independently of the icon. Example:
```
<ul class="selected-items">
    <li>
        <span class="nsdicon-close"></span>
        <span class="selected-item-label">Item 1</span>
    </li>
    <li>
        <span class="nsdicon-close"></span>
        <span class="selected-item-label">Item 2</span>
    </li>
</ul>
```

**Comment by manishjanky** [comment]
Let me have a look. Will update you soon.

**Comment by manishjanky** [comment]
Please update to `v0.8.0`
