### ISSUE TITLE
Value should not be a list with one element if multiple == false in config

### ISSUE THREAD

**Issue by AlexJMohr** [manishjanky/ngx-select-dropdown#53]
In template:
```html
<ngx-select-dropdown [(value)]="myValue" [multiple]="false" ...>
```
Results in `myValue` being `['whatever is selected']` instead of `'whatever is selected'`. Not sure if I did something wrong. If not, would it be a huge rework to make this happen?

**Comment by manishjanky** [comment]
Sorry for the delayed response. Was busy with other stuff. The feature is in dev already will be released with the next version. Please wait for it.

**Comment by manishjanky** [comment]
@AlexJMohr this has been fixed. Please update to `v1.0.0` . Please let me know if you still face issues.

Closing this.
