### ISSUE TITLE
Question: How do you dynamically select an item in ngx-select-dropdown from angular code?

### ISSUE THREAD

**Issue by aravinthchellathurai** [manishjanky/ngx-select-dropdown#58]
If I set the value as [ selectedValue ], the dropdown displays the selected node again in the dropdown list.

**Comment by manikantavarmaN** [comment]
Hi,
I am trying to bind an item to ng select dropdown  using ngmodel . It was successfully bound for  the first time . But when I try next time to assign new value it is not changing?
