### ISSUE TITLE
running cmd [ng build --prod] getting issue

### ISSUE THREAD

**Issue by tikemantns** [manishjanky/ngx-select-dropdown#59]
ERROR in node_modules/ngx-select-dropdown/dist/components/ngx-select-dropdown-component/ngx-select-dropdown.component.d.ts.SelectDropDownComponent.html(3,59): : Expected 0 arguments, but got 1.

Any update

**Comment by doubleH90** [comment]
What I have done is degrading the version of ngx-select-dropdown to 0.7.2, and it worked fine.

**Comment by AbdulKhader4123** [comment]
I am facing same issue in 1.4.4, but its working perfectly in 1.4.3.
