### ISSUE TITLE
Setting dataModel variable to [] removes it from the options list

### ISSUE THREAD

**Issue by NKatic** [manishjanky/ngx-select-dropdown#65]
Hello. When I set the dataModel variable in my controller to empty array, currently selected variable gets removed from the array of objects in the dropdown list. For example on button click I set dataModel=[] and as a result I now have one less row in the dropdown list. I'm on version 0.8.0.

Edit: I've tried setting the variable to an object from the options array and the same thing happens.

**Comment by VivekVWaghmare** [comment]
I am having the same issue

**Comment by manishjanky** [comment]
Let me have a look will update you soon

**Comment by manishjanky** [comment]
Please update to the latest version. This  has been fixed.
