### ISSUE TITLE
drop-down menu auto dropup according to screen position?

### ISSUE THREAD

**Issue by vedprakashpandey** [manishjanky/ngx-select-dropdown#66]
Hi,
I am facing issue on drop down menu position when my drop down button is bottom of screen all menu comes in bottom instead of top.
I think it should be top or bottom according to screen position as our normal html select box.

**Comment by askynet** [comment]
any updates?

**Comment by manishjanky** [comment]
Please update to `v3.1.0` this has been added to the component.
