### ISSUE TITLE
Dropdown view is not getting closed on Escape key press or focus another dropdown out using Tab key(PFA)

### ISSUE THREAD

**Issue by DGanapathi** [manishjanky/ngx-select-dropdown#68]
![image](https://user-images.githubusercontent.com/34437074/48332011-51f0ce00-e678-11e8-9c3f-99f8f3cfab7c.png)

**Comment by manishjanky** [comment]
Will update you soon on this.

**Comment by manishjanky** [comment]
@DGanapathi this has been fixed. Please update to latest version.
Note: `v1.0.0` may have breaking changes. Please read the docs
