### ISSUE TITLE
Plugin only works for hardcoded data sets

### ISSUE THREAD

**Issue by drewstaylor** [manishjanky/ngx-select-dropdown#7]
It would seem that loading options fails unless it is hardcoded into the component. Attempting to load an array of option data using ngOnInit() or directly into the class constructer throws an error; likewise, if you begin with dummy data and overwrite it in the constructor, changes to the data set won't be reflected in the template.

`ERROR Error: Not Defined: ngx-select-dropdown requires options. But got empty or undefined. `

Hardcoded data sets are not indicative of real world applications.

**Comment by manishjanky** [comment]
@drewstaylor have fixed this and published `v0.3.0 ` please update the package and use.

Thanks for your help 😄 . Let me know if you face any other issue.

Closing this.

**Comment by drewstaylor** [comment]
@manishjanky Very cool! I'll be testing it out this week, thanks.

**Comment by drewstaylor** [comment]
Can confirm this feature is now working.
