### ISSUE TITLE
how can i remove the items based on the first dropdown values?

### ISSUE THREAD

**Issue by bemes9226** [manishjanky/ngx-select-dropdown#71]

**Comment by bemes9226** [comment]
it is relationship between 1 dropdown to other dropdown,when i select first values needs to delete respective values in second dropdown

**Comment by manishjanky** [comment]
Thats something n you will have to achieve on your own code. Add a change event listener and as the 1st dropdown value changes filter out the options of the second dropdown. This will do the trick.
