### ISSUE TITLE
Cant to find any option to change the angle down icon class

### ISSUE THREAD

**Issue by rhenryrobert** [manishjanky/ngx-select-dropdown#73]
How to change the dropdown arrow class. Current class is "nsdicon-angle-down".. I want to update this class to "fa fa-angle-down".. Is this possible ???

**Comment by nehal076** [comment]
@manishjanky I want to change the size of the `nsdicon-angle-down` icon, and I tried using this CSS, it doesn't work. I'm using version `"ngx-select-dropdown": "^1.4.4"`. Any suggestions on how to do it?
