### ISSUE TITLE
Direction

### ISSUE THREAD

**Issue by mohebbisaeed** [manishjanky/ngx-select-dropdown#75]
plaese add rtl direction to the @input()

**Comment by manishjanky** [comment]
Can you please elaborate a bit. What is that you are trying to achieve?

**Comment by mohebbisaeed** [comment]
Your component is just left. Put the @Input() variable to change the right or left position. Direction statically  in the CSS

**Comment by manishjanky** [comment]
Update to latest version.. and so sorry for not able to bring this in early..
