### ISSUE TITLE
Add dropdown Options - Change not detected

### ISSUE THREAD

**Issue by OPunktSchmidt** [manishjanky/ngx-select-dropdown#77]
Hey,

when i add my dropdown options in ngOnInit it works perfect:

```
  ngOnInit() {

    this.apiService.getAllActivities().subscribe(response => {
      this.activities = response;
      this.activityDropDownOptions = response;
    });
  }
```

But when i want to add new options after a change event i does not work. The new options are not displayed:
```

  activityDropDownSelectionChanged(event: any) {

    this.questionnaireDropDownOptions = []

    for (let activity of event.value) {
      this.apiService.getActivity(activity.id).subscribe(response => {

        for (let organisationalUnitQuestionnaire of response.organisationalUnitQuestionnaires) {
          this.questionnaireDropDownOptions.push(organisationalUnitQuestionnaire);
        }
      });
    }
  }
```

Is this  bug or i'm doing something wrong?

**Comment by manishjanky** [comment]
Hey there,

This is not a bug. And you are not doing anything wrong. Its just you are missing one thing. Please see the code below. This will sove your problem. As the options are passed by refernce and when pushing elements actually wont trigger the change. You need to assign a new value to it.
```
activityDropDownSelectionChanged(event: any) {

    this.questionnaireDropDownOptions = []

    for (let activity of event.value) {
      this.apiService.getActivity(activity.id).subscribe(response => {

        for (let organisationalUnitQuestionnaire of response.organisationalUnitQuestionnaires) {
          this.questionnaireDropDownOptions.push(organisationalUnitQuestionnaire);
          **this.questionnaireDropDownOptions = [...this.questionnaireDropDownOptions];**
        }
      });
    }
  }
```

**Comment by fabio-percivaldi** [comment]
Hi, i'm not sure about what i'm saying but when the config are initialized the limitTo is set to the length of the option list.
```private initDropdownValuesAndOptions() {
    const config: any = {
      displayKey: "description",
      height: 'auto',
      search: false,
      placeholder: 'Select',
      searchPlaceholder: 'Search',
      limitTo: this.options.length,
      customComparator: undefined,
      noResultsFound: 'No results found!',
      moreText: 'more',
      searchOnKey: null
    }; 
```
Let's say for instance that when you create the list you have only one item, if you then push a new option (even if you assign a new value) the limitTo is already set to be 1 and is never reassigned, so only one element is displayed.

I tried to push 100 empty element on the init of the config and if you add new values it works.

It also works if you manually set the limitTo to an higher value. 

I think this is the portion of code that generate this problem : 
```
<li #availableOption *ngFor="let item of availableItems| filterBy: searchText : config.searchOnKey | limitTo : config.limitTo;let i = index"
                tabindex="-1" [ngClass]="{'active': focusedItemIndex == i}" (click)="selectItem(item,i)">
                {{item[config.displayKey] || item}}</li>
```

forgive me if this doesn't make any sense.

**Comment by manishjanky** [comment]
@fabio-percivaldi I understand what you are trying say. If you check my previous reply. They below piece of code is you key.

```
for (let organisationalUnitQuestionnaire of response.organisationalUnitQuestionnaires) {
          this.questionnaireDropDownOptions.push(organisationalUnitQuestionnaire);
          this.questionnaireDropDownOptions = [...this.questionnaireDropDownOptions];
     }
```
Inside the above code the second statement i.e.
````
this.questionnaireDropDownOptions = [...this.questionnaireDropDownOptions];
````

Will solve you problem. Please let me know if you need further help.

**Comment by ish2028** [comment]
This solution does not work for me.  I am insert new objects and reassigning the `options` but the new entry is not populating.
