### ISSUE TITLE
Show all selected items

### ISSUE THREAD

**Issue by donpironet** [manishjanky/ngx-select-dropdown#78]
Is there a way to let the component show all selected items. Now it only shows the first one and the + X more. 

How can I show all the items selected?

**Comment by manishjanky** [comment]
As of now there is no way. Let me see if thats vaiable will update you on the same.

**Comment by manishjanky** [comment]
This feature may not be viable as this will increase the design complexity of the dropdown as it will have to display all the selected options and optimizing that will be quite complex. But I'm open for any suggestion if you have and the same is not too complex. Closing this but as I said open for suggestions.

**Comment by goldel777** [comment]
THe other issue I am seeing, when the dropdown is available for selection, if it exceeds the 'body', it will not be displayed.
