### ISSUE TITLE
Unable to disable dropdown

### ISSUE THREAD

**Issue by Subru97** [manishjanky/ngx-select-dropdown#79]
I'm trying to disable dropdown based on condition in Angular. I tried various methods to disable ngx-select-dropdown but it didn't work and there is no information regarding this in the docs. Is there anyway to disable the dropdown?

**Comment by manishjanky** [comment]
Yes there is you can just use this css on the element <ngx-select-dropdown></ngx-select-dropdown>
`    pointer-events: none;`

And then you can style it acccordingly for other css related things.

**Comment by Subru97** [comment]
Yeah I already discovered this and it works. But what I'm asking for is a disable attribute like in any other drop down.

**Comment by manishjanky** [comment]
OK let me see.

**Comment by manishjanky** [comment]
Please update to latest version. This has been implemented.

**Comment by a30001735** [comment]
How to disable in reactive forms?
