### ISSUE TITLE
Last option will be deleted when selecting a random option

### ISSUE THREAD

**Issue by Jennilein1991** [manishjanky/ngx-select-dropdown#8]
Hello  😃 ,
i implemented your nice dropdown in my angular 5 application but everytime when i select an item in the list the last object in the list will be deleted.
For example when i have the following options array:
`[{ "Name": "Female", "id": 0 }, { "Name": "test2", "id": 2 }, { "Name": "Male", "id": 1 }, { "Name": "test", "id": 2 }];`
with "Name" as the main key.
When i now select for example "Female", the entry "test" will be deleted in the list:

![image](https://user-images.githubusercontent.com/12052402/39213573-3f8ceb5e-4812-11e8-8883-a8b870a3704a.png)
![image](https://user-images.githubusercontent.com/12052402/39213618-589389dc-4812-11e8-8126-70915cbc5f4f.png)

Just when i search for "test" it occurs.

Kind regards
Jenni

**Comment by manishjanky** [comment]
@Jennilein1991 let me have a look and will update you soon on this.

**Comment by manishjanky** [comment]
@Jennilein1991 have fixed this issue. will be publishing a new version ASAP. Will close the issue once done.

Thanks for your help in pointing this out.

**Comment by manishjanky** [comment]
Fixed this with `v0.3.1`. Please update and use.

Thanks :)
