### ISSUE TITLE
Dropdown view is getting opened even it is Disabled.

### ISSUE THREAD

**Issue by DGanapathi** [manishjanky/ngx-select-dropdown#81]
Goto [demo page](https://manishjanky.github.io/ngx-select-dropdown/) and press TAB key until it reaches the disabled dropdown and press Tab key or down arrow to see
![image](https://user-images.githubusercontent.com/34437074/50512484-2dca3e80-0ab8-11e9-989d-4fb3007b75df.png)

**Comment by manishjanky** [comment]
Fixed.

Please update to latest version.
