### ISSUE TITLE
In IE11 & Edge browsers, Navigation between dropdown options using up&down arrows from keyboard not working

### ISSUE THREAD

**Issue by DGanapathi** [manishjanky/ngx-select-dropdown#82]
In IE11 & Edge browsers, Navigation between dropdown options using up&down arrows from keyboard not working.
And in Edge browser view is not getting closed on Escape key press.

**Comment by manishjanky** [comment]
This is an issue with IE and Edge. They dont work well with KeyDown events. As here i have to listen to key down events when target is the dropdown component and when target is outside the component. But IE and Edge only listen to keydown events on window object. Trying to figure out a way. Will update you.

**Comment by manishjanky** [comment]
Fixed.

Please update to latest version.
