### ISSUE TITLE
Disable Google autofill

### ISSUE THREAD

**Issue by sneyyar** [manishjanky/ngx-select-dropdown#86]
The chrome browser use some heuristic  algorithm to autofill the search input, resulting in second dropdown, that hides the original one. This could be very annoying to users. It went away after changing the "name" of input from "search"  to   a random name  'sbox'.  Hope this would improve the usability.

**Comment by manishjanky** [comment]
Let me have a look. Will update soon.

**Comment by IvanRyavkin** [comment]
Hi! Tell me when it's possible.

**Comment by manishjanky** [comment]
Please update to `v1.1.0`
