### ISSUE TITLE
How to show Multiple display Key 

### ISSUE THREAD

**Issue by vedprakashpandey** [manishjanky/ngx-select-dropdown#88]
Hi,

Is there any way to display multiple key in display key option. In my application requirement I have to display both name and id in drop down.

**Comment by RsknCankov** [comment]
Hello, 
I am working on a project in which I also need to have the option for displaying multiple fields in display key, do you plan to provide that feature in the near future?

**Comment by p30patel** [comment]
You can do with your custom property of array/ object. 
For example : 

- Let say you have Person (id, firastName, lastName, age) array/ object.  

- Create new custom property as : name of Person object and set values as : firstName + lastName

- Use Person ( (id, firastName, lastName, name, age) array/object and dispayKey as : name

**Comment by pathikvejani** [comment]
@p30patel Please give an example.

**Comment by manishjanky** [comment]
What @p30patel suggested is the correct and the same can be used to achieve what is requested. For eg..
```
const options=[
{
   firstName: 'User',
   lastName: 'surname'
}
]

options.forEach((opt)=>{
   opt.displayThisKey = `${opt.firstName} ${opt.lastName}`
})
```

Hence closing this issue.

**Comment by Jamshed7664** [comment]
Can we pass image ?
