### ISSUE TITLE
CSS on ngx-select-dropdown

### ISSUE THREAD

**Issue by sans30** [manishjanky/ngx-select-dropdown#89]
Hi Manish,

I am using reactive form and have below CSS classes defined for .ng-valid & .ng-dirty. When I tried with v1.0.1, validation appear to work fine. But the solid green strip appear on above the select drop down instead in the drop down itself. could you please let me know if you have any workaround for this.

.ng-dirty:not(form)  {
    border-left: 5px solid #a94442; /* red */
 }

 .ng-valid:not(form)  {
    border-left: 5px solid green; /* red */
 }

Thanks,
sans30

**Comment by manishjanky** [comment]
let me have a look. Will update you soon.

**Comment by manishjanky** [comment]
Please refer #94 you need to over ride the styles in your global stylesheet.
