### ISSUE TITLE
Clear selected items not working properly in latest version(1.0.1)

### ISSUE THREAD

**Issue by DGanapathi** [manishjanky/ngx-select-dropdown#90]
Selection is not clearing on clear button click.
Please find below code and link 
`<ngx-select-dropdown tabindex="0" (change)="changeValue($event)" [multiple]="true" [(ngModel)]="multiSelect" [config]="config"
				 [options]="options"></ngx-select-dropdown>`

`onClearClick() {
    this.multiSelect  = [];
    this.options = [...this.options];
  }`

[https://stackblitz.com/edit/angular-ptsyhe](https://stackblitz.com/edit/angular-ptsyhe)

**Comment by EduardoDominguez** [comment]
I have the same problem. How can i clear the current selection?

**Comment by DakshKhetarpal** [comment]
i have the same issue. Any update?

**Comment by satyendersaini56** [comment]
Any update?

**Comment by kashifsohail** [comment]
Same Issue is here?

**Comment by DakshKhetarpal** [comment]
Hey guys i was able to solve the problem using form control remove and add control in angular .
When the button is pressed i removed control and in a separate thread i added control back to the dropdown therefore refreshing the dropdown.

**Comment by fredvaliant** [comment]
Any update on this issue. 

DakshKheTarpal, can you show your workaround.

**Comment by aruljayaraj** [comment]
@manishjanky Any update this issue? I'm using a reactive form. How could I clear the selected values of ngx-select-dropdown when I change the previous dropdown changes? 
In my html:
<ngx-select-dropdown 
                            (change)="onItemSelect($event)" 
                            formControlName="app_component" 
                            [multiple]="true" 
                            [config]="config"
                             [options]="ApplicationComponent"
                            ></ngx-select-dropdown>
In my ts file:
During on change of previous dropdown I'm tring to reset the selected values of ngx-select-dropdown

onChangeApplicationArea(event: any, sector: string, area: string): void {
    this.ApplicationComponent = [];
    this.ursFrm.patchValue({app_component: '' });
    console.log(this.ApplicationComponent);
  }

**Comment by datnqvn** [comment]
I have same issue and looking for the update

**Comment by a30001735** [comment]
Guys, any update found for this? Or should we not use Reactive forms with this component?

**Comment by manishjanky** [comment]
Sorry Guys for the delay.. Was not in a state to look into things.. Will give guys a update soon..

**Comment by manishjanky** [comment]
Please update to `v1.1.0`.

**Comment by bansalanjali** [comment]
Hey guys , I found solution for clear selected item.
you just have to create a function and call on submit button.
e.g,
Html file:
`<ngx-select-dropdown class="form-control_Dropdown"  placeholder="Select Category"(change)="selectionChanged($event)" [multiple]="true" [config]="configForMultidropdown"
                  [(ngModel)]="mapCategoryForm.categories" [options]="categoryList"></ngx-select-dropdown>`
________________________________________________________________

Ts file:
` resetCategoryList() {
    this.mapCategoryForm.categories = [];  // your ngModel list
  }`
