### ISSUE TITLE
customize button close ngx-select-dropdown

### ISSUE THREAD

**Issue by vovanlong** [manishjanky/ngx-select-dropdown#91]
Hi, I'm newbee with angular, I just used ngx-select-dropdown.I can't customize button close in the picture. 
I want display:none ul li of button close.  Any suggestion????? thanks a lot 
![export](https://user-images.githubusercontent.com/36064862/52043575-a9655280-2572-11e9-8ef4-c1a5afce646a.png)

**Comment by manishjanky** [comment]
Duplicate of #94 

Please refer the mentioned issues. You can override the style in your global stylesheet.
