### ISSUE TITLE
Cannot change the value through ts code.

### ISSUE THREAD

**Issue by tarun04** [manishjanky/ngx-select-dropdown#92]
Angular 2+
.html
[(ngModel)]=''component.value"

.ts 
component.value = ''some new value''

Doesn't work as expected. Am I configuring something wrong on the html?

**Comment by juhana** [comment]
This is the only way I could get it working. You need to reset the options list after setting the value to force the component to refresh.

```
<ngx-select-dropdown [(ngModel)]="component.value" [options]="options">

this.component.value = "some new value";
setTimeout(() => this.options = [...this.options], 1);
```

**Comment by manishjanky** [comment]
Duplicate of #95
