### ISSUE TITLE
how to change styling of select box

### ISSUE THREAD

**Issue by Nykz** [manishjanky/ngx-select-dropdown#94]
![issue](https://user-images.githubusercontent.com/19989930/52805327-5a5c0900-30ac-11e9-81d3-970991ab5622.png)

tried this
ngx-select-dropdown {
  float: left;
  width: 100%;
  height: 61px;
  padding: 0 15px;
  border: 2px solid #e8ecec;
  font-size: 13px !important;
  color: #888888;
  -webkit-border-radius: 8px;
  -moz-border-radius: 8px;
  -ms-border-radius: 8px;
  -o-border-radius: 8px;
  border-radius: 8px;
}

But not working as expected, it is just making an outer layer for the select box
So please let me know how to achieve that. Its really urgent

**Comment by anapanadero** [comment]
Maybe if you apply these styles in .ngx-dropdown-button works.

**Comment by Nykz** [comment]
No, dint work for me

**Comment by bsrafael** [comment]
I have the same issue. I want to override the default layout, but can't seem to find any way to do it. Any updates on this issue?

**Comment by aruljayaraj** [comment]
@bsrafael You've to overwrite the  .ngx-dropdown-button CSS on the global stylesheet, not in the component stylesheet. It works for me.

**Comment by bsrafael** [comment]
> @bsrafael You've to overwrite the .ngx-dropdown-button CSS on your global stylesheet, not in the component stylesheet. It works for me.

Thanks, I've done it and it worked.
I was hoping for a cleaner, built-in way, though.
