### ISSUE TITLE
Selected options disappers

### ISSUE THREAD

**Issue by samata-cdmx** [manishjanky/ngx-select-dropdown#96]
Hi,

After adding height in the config object, if we try to scroll through options after selecting one the selected oiption disappers and empty white space can be seen
![image](https://user-images.githubusercontent.com/35131382/52931567-de471700-3372-11e9-9b0f-bffe9972f1f1.png)

How to resolve this?

**Comment by manishjanky** [comment]
@samata-cdmx  can you please create a demo replicating this on Stackblitz.. Not able to replicate on my end..
