### ISSUE TITLE
css ngx-dropdown-container

### ISSUE THREAD

**Issue by Bhuvn12** [manishjanky/ngx-select-dropdown#98]
max-width is not working on ngx-dropdown-container . I am trying to set max-width like below method.
    .ngx-dropdown-container{
        width: 150px;
        max-width: 170px;
        overflow: hidden;
    }
But this is not working.

**Comment by saurabBajgain** [comment]
ngx-select-dropdown,
.ngx-dropdown-button{  
  max-width: 220px;
}
this one is working for me....

**Comment by a30001735** [comment]
Hi I am trying to hide the border using something like this, but it doesnt seem to work. 
Your correct, the width does change with what you suggested. Any way on how to change or remove the border.

```
.ngx-select-dropdown, .ngx-dropdown-button {
  border: none;
}

```

**Comment by manishjanky** [comment]
Please put in your css inside style.css i.e the global stylesheet. If you try this on component level may not work. Also try considering the `!important ` specifier.
